import SierpinskiFormal.DigitSupportCardinality

set_option autoImplicit false

/-!
# Exact support counts and radix blocks

The canonical digit-product series has exactly as many supported coefficients
below a radix power as there are words in its nonzero digit set.  The same
digit decomposition gives a coefficient factorization across aligned radix
blocks and zero cylinders generated by a missing digit.
-/

namespace IndependentZeroBlocks

open SierpinskiFormal

private theorem digitSupport_mul_supportCount_le_next
    {K : Type*} [Field K] (b : ℕ) (hb : 2 ≤ b)
    (A : Polynomial K) (hA0 : A.coeff 0 = 1) (e : ℕ) :
    radixDigitSupportCount b A *
        supportCount (canonicalSeries b A) (b ^ e) ≤
      supportCount (canonicalSeries b A) (b ^ (e + 1)) := by
  classical
  let D := (Finset.range b).filter fun d => A.coeff d ≠ 0
  let Q := (Finset.range (b ^ e)).filter fun m =>
    PowerSeries.coeff m (canonicalSeries b A) ≠ 0
  let T := D ×ˢ Q
  let S := (Finset.range (b ^ (e + 1))).filter fun n =>
    PowerSeries.coeff n (canonicalSeries b A) ≠ 0
  let g : ℕ × ℕ → ℕ := fun p => b * p.2 + p.1
  have hg : ∀ p ∈ T, g p ∈ S := by
    intro p hp
    have hp' := hp
    simp only [T, D, Q, Finset.mem_product, Finset.mem_filter,
      Finset.mem_range] at hp'
    have hlt : g p < b ^ (e + 1) := by
      calc
        g p = b * p.2 + p.1 := rfl
        _ < b * p.2 + b := Nat.add_lt_add_left hp'.1.1 _
        _ = b * (p.2 + 1) := by ring
        _ ≤ b * b ^ e :=
          Nat.mul_le_mul_left b (Nat.succ_le_iff.mpr hp'.2.1)
        _ = b ^ (e + 1) := by rw [pow_succ]; ac_rfl
    have hcoeff :
        PowerSeries.coeff (g p) (canonicalSeries b A) ≠ 0 := by
      rw [show g p = b * p.2 + p.1 by rfl]
      rw [coeff_canonicalSeries_mul_add b hb A hA0 p.2 p.1 hp'.1.1]
      exact mul_ne_zero hp'.2.2 hp'.1.2
    simp only [S, Finset.mem_filter, Finset.mem_range]
    exact ⟨hlt, hcoeff⟩
  have ginj : (T : Set (ℕ × ℕ)).InjOn g := by
    intro p hp q hq hpq
    have hp' := hp
    have hq' := hq
    simp only [Finset.mem_coe, T, D, Q, Finset.mem_product,
      Finset.mem_filter, Finset.mem_range] at hp' hq'
    have hfst : p.1 = q.1 := by
      have hmod := congrArg (fun n => n % b) hpq
      simpa [g, Nat.mul_add_mod, Nat.mod_eq_of_lt hp'.1.1,
        Nat.mod_eq_of_lt hq'.1.1] using hmod
    have hmul : b * p.2 = b * q.2 := by
      change b * p.2 + p.1 = b * q.2 + q.1 at hpq
      rw [hfst] at hpq
      exact Nat.add_right_cancel hpq
    have hsnd : p.2 = q.2 :=
      Nat.mul_left_cancel (by omega) hmul
    exact Prod.ext hfst hsnd
  have hcard := Finset.card_le_card_of_injOn g hg ginj
  simpa [T, D, Q, S, supportCount, radixDigitSupportCount,
    Finset.card_product] using hcard

/-- Below the first `e` radix positions, the support of the canonical series
has exactly one element for every word of length `e` in the set of nonzero
radix digits. -/
theorem supportCount_canonicalSeries_pow_eq_digitSupport
    {K : Type*} [Field K] (b : ℕ) (hb : 2 ≤ b)
    (A : Polynomial K) (hA0 : A.coeff 0 = 1) (e : ℕ) :
    supportCount (canonicalSeries b A) (b ^ e) =
      radixDigitSupportCount b A ^ e := by
  induction e with
  | zero =>
      classical
      change ((Finset.range 1).filter fun n =>
        PowerSeries.coeff n (canonicalSeries b A) ≠ 0).card = 1
      rw [show (Finset.range 1).filter (fun n =>
          PowerSeries.coeff n (canonicalSeries b A) ≠ 0) = {0} by
        ext n
        simp only [Finset.mem_filter, Finset.mem_range,
          Finset.mem_singleton]
        constructor
        · intro hn
          omega
        · intro hn
          subst n
          simp]
      simp
  | succ e ih =>
      apply le_antisymm
      · exact supportCount_canonicalSeries_pow_le_digitSupport b hb A hA0 (e + 1)
      · calc
          radixDigitSupportCount b A ^ (e + 1) =
              radixDigitSupportCount b A *
                radixDigitSupportCount b A ^ e := by
            rw [pow_succ]
            ac_rfl
          _ = radixDigitSupportCount b A *
                supportCount (canonicalSeries b A) (b ^ e) := by rw [ih]
          _ ≤ supportCount (canonicalSeries b A) (b ^ (e + 1)) :=
            digitSupport_mul_supportCount_le_next b hb A hA0 e

/-- Splitting an index after `e` low radix digits factors the canonical
coefficient into its high-block and low-block coefficients. -/
theorem coeff_canonicalSeries_pow_mul_add
    {K : Type*} [Field K] (b : ℕ) (hb : 2 ≤ b)
    (A : Polynomial K) (hA0 : A.coeff 0 = 1)
    (e q r : ℕ) (hr : r < b ^ e) :
    PowerSeries.coeff (b ^ e * q + r) (canonicalSeries b A) =
      PowerSeries.coeff q (canonicalSeries b A) *
        PowerSeries.coeff r (canonicalSeries b A) := by
  induction e generalizing q r with
  | zero =>
      have hr0 : r = 0 := by simpa using hr
      subst r
      simp
  | succ e ih =>
      have hbpos : 0 < b := by omega
      have hd : r % b < b := Nat.mod_lt r hbpos
      have hm : r / b < b ^ e := by
        apply (Nat.div_lt_iff_lt_mul hbpos).2
        simpa [pow_succ, Nat.mul_comm] using hr
      have hsplit : b * (r / b) + r % b = r := Nat.div_add_mod r b
      have hindex :
          b ^ (e + 1) * q + r =
            b * (b ^ e * q + r / b) + r % b := by
        calc
          b ^ (e + 1) * q + r =
              b * (b ^ e * q) + (b * (r / b) + r % b) := by
            rw [hsplit, pow_succ]
            ring
          _ = b * (b ^ e * q + r / b) + r % b := by ring
      rw [hindex]
      rw [coeff_canonicalSeries_mul_add b hb A hA0
        (b ^ e * q + r / b) (r % b) hd]
      rw [ih q (r / b) hm]
      rw [mul_assoc]
      rw [← coeff_canonicalSeries_mul_add b hb A hA0
        (r / b) (r % b) hd]
      rw [hsplit]

/-- A zero radix digit forces a zero coefficient cylinder inside every aligned
block, at every depth. -/
theorem coeff_canonicalSeries_eq_zero_on_missingDigit_cylinder
    {K : Type*} [Field K] (b : ℕ) (hb : 2 ≤ b)
    (A : Polynomial K) (hA0 : A.coeff 0 = 1)
    (d : ℕ) (hd : d < b) (hAd : A.coeff d = 0)
    (k q r : ℕ) (hr : r < b ^ k) :
    PowerSeries.coeff (b ^ (k + 1) * q + d * b ^ k + r)
        (canonicalSeries b A) = 0 := by
  have hlow : d * b ^ k + r < b ^ (k + 1) := by
    calc
      d * b ^ k + r < d * b ^ k + b ^ k :=
        Nat.add_lt_add_left hr _
      _ = (d + 1) * b ^ k := by ring
      _ ≤ b * b ^ k :=
        Nat.mul_le_mul_right (b ^ k) (Nat.succ_le_iff.mpr hd)
      _ = b ^ (k + 1) := by rw [pow_succ]; ac_rfl
  rw [show b ^ (k + 1) * q + d * b ^ k + r =
      b ^ (k + 1) * q + (d * b ^ k + r) by ring]
  rw [coeff_canonicalSeries_pow_mul_add b hb A hA0
    (k + 1) q (d * b ^ k + r) hlow]
  rw [show d * b ^ k + r = b ^ k * d + r by ring]
  rw [coeff_canonicalSeries_pow_mul_add b hb A hA0 k d r hr]
  have hcoeffd :
      PowerSeries.coeff d (canonicalSeries b A) = A.coeff d := by
    simpa [hA0] using
      coeff_canonicalSeries_mul_add b hb A hA0 0 d hd
  rw [hcoeffd, hAd]
  simp

end IndependentZeroBlocks
