import Mathlib.Analysis.InnerProductSpace.MeanErgodic
import Mathlib.Analysis.LocallyConvex.WeakSpace
import Mathlib.Analysis.Normed.Module.Dual

/-!
# Mean ergodic convergence from a weak cluster of averages

This file supplies a general normed-space analytic component of the proposed
density extension. It does not assert that a recognizable support has a
reflexive representation or a weakly compact translation orbit.
-/

noncomputable section

open Filter Finset Function Bornology
open scoped Topology

namespace IndependentZeroBlocks

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- Cesaro averages tend to zero on the closure of the range of `T - 1`. -/
theorem tendsto_birkhoffAverage_zero_of_mem_closure_range
    (T : E →L[ℝ] E) (hT : LipschitzWith 1 T) {x : E}
    (hx : x ∈ closure (LinearMap.range (T.toLinearMap - 1) : Set E)) :
    Tendsto (birkhoffAverage ℝ T id · x) atTop (𝓝 0) := by
  have hc : IsClosed {y : E | Tendsto (birkhoffAverage ℝ T id · y) atTop (𝓝 0)} :=
    isClosed_setOf_tendsto_birkhoffAverage ℝ hT uniformContinuous_id continuous_const
  refine closure_minimal (Set.forall_mem_range.2 fun y ↦ ?_) hc hx
  have hb : IsBounded (Set.range (id <| T^[·] y)) :=
    isBounded_iff_forall_norm_le.2 ⟨‖y‖, Set.forall_mem_range.2 fun n ↦ by
      have hz : T^[n] 0 = 0 := iterate_map_zero (T : E →+ E) n
      simpa [hz] using (hT.iterate n).dist_le_mul y 0⟩
  have hs : ∀ n x y, T^[n] (x - y) = T^[n] x - T^[n] y :=
    iterate_map_sub (T : E →+ E)
  simpa [birkhoffAverage, birkhoffSum, Finset.sum_sub_distrib, smul_sub, hs]
    using tendsto_birkhoffAverage_apply_sub_birkhoffAverage ℝ hb

/-- A fixed point in the same closed coboundary coset is the norm limit. -/
theorem tendsto_birkhoffAverage_of_fixed_sub_mem_closure_range
    (T : E →L[ℝ] E) (hT : LipschitzWith 1 T) {x a : E}
    (ha : IsFixedPt T a)
    (hxa : x - a ∈ closure (LinearMap.range (T.toLinearMap - 1) : Set E)) :
    Tendsto (birkhoffAverage ℝ T id · x) atTop (𝓝 a) := by
  have hzero := tendsto_birkhoffAverage_zero_of_mem_closure_range T hT hxa
  have hfix := ha.tendsto_birkhoffAverage ℝ id
  have hs : ∀ n x y, T^[n] (x + y) = T^[n] x + T^[n] y :=
    iterate_map_add (T : E →+ E)
  have heq : x - a + a = x := sub_add_cancel _ _
  have havg : ∀ n, birkhoffAverage ℝ T id n (x - a) +
      birkhoffAverage ℝ T id n a = birkhoffAverage ℝ T id n x := by
    intro n
    conv_rhs => rw [← heq]
    simp [birkhoffAverage, birkhoffSum, hs, Finset.sum_add_distrib, smul_add, smul_sub]
  simpa only [havg, id_eq, zero_add] using hzero.add hfix

/-- Every positive average differs from its initial vector by a coboundary. -/
theorem birkhoffAverage_sub_mem_range (T : E →L[ℝ] E) (x : E) {n : ℕ}
    (hn : n ≠ 0) :
    birkhoffAverage ℝ T id n x - x ∈ LinearMap.range (T.toLinearMap - 1) := by
  let V := LinearMap.range (T.toLinearMap - 1)
  change birkhoffAverage ℝ T id n x - x ∈ V
  have hiter : ∀ k, T^[k] x - x ∈ V := by
    intro k
    induction k with
    | zero => simp [V]
    | succ k ih =>
      have hstep : T (T^[k] x) - T^[k] x ∈ V :=
        LinearMap.mem_range.mpr ⟨T^[k] x, rfl⟩
      simpa [Function.iterate_succ_apply', sub_add_sub_cancel] using V.add_mem hstep ih
  have hh := V.smul_mem (n : ℝ)⁻¹ (V.sum_mem fun k (_ : k ∈ range n) ↦ hiter k)
  have hn' : (n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hn
  simpa [birkhoffAverage, birkhoffSum, Finset.sum_sub_distrib, smul_sub,
    ← Nat.cast_smul_eq_nsmul ℝ, inv_smul_smul₀ hn'] using hh

/-- Applying `T` to an average is the average with initial vector `T x`. -/
theorem map_birkhoffAverage_initial (T : E →L[ℝ] E) (x : E) (n : ℕ) :
    T (birkhoffAverage ℝ T id n x) = birkhoffAverage ℝ T id n (T x) := by
  have hh : ∀ k, T (T^[k] x) = T^[k] (T x) := by
    intro k
    exact (Function.iterate_succ_apply' T k x).symm.trans
      (Function.iterate_succ_apply T k x)
  simp [birkhoffAverage, birkhoffSum, map_sum, hh]

/-- A weak limit of Cesaro averages along a cofinal filter is already their
norm limit. The hypothesis is expressed by all continuous real functionals;
the filter need not be generated by a subsequence. -/
theorem tendsto_birkhoffAverage_of_weak_limit
    (T : E →L[ℝ] E) (hT : LipschitzWith 1 T) (x a : E)
    (F : Filter ℕ) [NeBot F] (hF : F ≤ atTop)
    (ha : ∀ l : E →L[ℝ] ℝ,
      Tendsto (fun n ↦ l (birkhoffAverage ℝ T id n x)) F (𝓝 (l a))) :
    Tendsto (birkhoffAverage ℝ T id · x) atTop (𝓝 a) := by
  have hb : IsBounded (Set.range (id <| T^[·] x)) :=
    isBounded_iff_forall_norm_le.2 ⟨‖x‖, Set.forall_mem_range.2 fun n ↦ by
      have hz : T^[n] 0 = 0 := iterate_map_zero (T : E →+ E) n
      simpa [hz] using (hT.iterate n).dist_le_mul x 0⟩
  have hres : Tendsto (fun n ↦ T (birkhoffAverage ℝ T id n x) -
      birkhoffAverage ℝ T id n x) F (𝓝 0) := by
    simpa only [map_birkhoffAverage_initial] using
      (tendsto_birkhoffAverage_apply_sub_birkhoffAverage ℝ hb).mono_left hF
  have hfixed : IsFixedPt T a := by
    apply (NormedSpace.eq_iff_forall_dual_eq ℝ).mpr
    intro l
    have h1 := (ha (l.comp T)).sub (ha l)
    have h2 := l.continuous.continuousAt.tendsto.comp hres
    have he : l (T a) - l a = 0 := by
      apply tendsto_nhds_unique h1
      simpa only [Function.comp_def, ContinuousLinearMap.comp_apply, map_sub, map_zero] using h2
    exact sub_eq_zero.mp he
  have hweak : Tendsto (fun n ↦ toWeakSpace ℝ E (birkhoffAverage ℝ T id n x - x))
      F (𝓝 (toWeakSpace ℝ E (a - x))) := by
    have hinj : Function.Injective (topDualPairing ℝ E).flip := by
      intro u v huv
      apply (NormedSpace.eq_iff_forall_dual_eq ℝ).mpr
      intro l
      exact LinearMap.congr_fun huv l
    apply (WeakBilin.tendsto_iff_forall_eval_tendsto _ hinj).mpr
    intro l
    change Tendsto (fun n ↦ l (birkhoffAverage ℝ T id n x - x)) F
      (𝓝 (l (a - x)))
    simpa only [map_sub] using (ha l).sub_const (l x)
  let V := LinearMap.range (T.toLinearMap - 1)
  have hmem : ∀ᶠ n in F, toWeakSpace ℝ E (birkhoffAverage ℝ T id n x - x) ∈
      toWeakSpace ℝ E '' (V : Set E) := by
    filter_upwards [hF (eventually_ne_atTop 0)] with n hn
    exact ⟨_, birkhoffAverage_sub_mem_range T x hn, rfl⟩
  have hc : toWeakSpace ℝ E (a - x) ∈ closure (toWeakSpace ℝ E '' (V : Set E)) :=
    mem_closure_of_tendsto hweak hmem
  rw [← V.convex.toWeakSpace_closure ℝ] at hc
  obtain ⟨y, hy, he⟩ := hc
  have hay : y = a - x := (toWeakSpace ℝ E).injective he
  have hax : a - x ∈ closure (V : Set E) := hay ▸ hy
  have hxa : x - a ∈ closure (V : Set E) := by
    have hh : -(a - x) ∈ closure (V : Set E) :=
      map_mem_closure continuous_neg hax (fun _ hz ↦ V.neg_mem hz)
    simpa only [neg_sub] using hh
  exact tendsto_birkhoffAverage_of_fixed_sub_mem_closure_range T hT hfixed hxa

/-- A weak cluster point of the Cesaro averages is their norm limit. -/
theorem tendsto_birkhoffAverage_of_weak_mapClusterPt
    (T : E →L[ℝ] E) (hT : LipschitzWith 1 T) (x a : E)
    (ha : MapClusterPt (toWeakSpace ℝ E a) atTop
      (fun n ↦ toWeakSpace ℝ E (birkhoffAverage ℝ T id n x))) :
    Tendsto (birkhoffAverage ℝ T id · x) atTop (𝓝 a) := by
  let u := fun n ↦ toWeakSpace ℝ E (birkhoffAverage ℝ T id n x)
  let F : Filter ℕ := comap u (𝓝 (toWeakSpace ℝ E a)) ⊓ atTop
  haveI : NeBot F := neBot_inf_comap_iff_map'.mpr ha
  have hu : Tendsto u F (𝓝 (toWeakSpace ℝ E a)) :=
    tendsto_iff_comap.mpr (show F ≤ comap u (𝓝 (toWeakSpace ℝ E a)) from inf_le_left)
  apply tendsto_birkhoffAverage_of_weak_limit T hT x a F inf_le_right
  intro l
  exact (WeakBilin.eval_continuous (topDualPairing ℝ E).flip l).tendsto _ |>.comp hu

/-- Weak compactness of a set containing the averages guarantees their norm
convergence. This is the mean ergodic component used by the density route;
the compactness premise must be proved for the application. -/
theorem exists_tendsto_birkhoffAverage_of_weakly_compact
    (T : E →L[ℝ] E) (hT : LipschitzWith 1 T) (x : E)
    (C : Set (WeakSpace ℝ E)) (hC : IsCompact C)
    (hmem : ∀ᶠ n in atTop, toWeakSpace ℝ E (birkhoffAverage ℝ T id n x) ∈ C) :
    ∃ a : E, Tendsto (birkhoffAverage ℝ T id · x) atTop (𝓝 a) := by
  obtain ⟨a, _, ha⟩ := hC.exists_mapClusterPt (tendsto_principal.mpr hmem)
  exact ⟨(toWeakSpace ℝ E).symm a,
    tendsto_birkhoffAverage_of_weak_mapClusterPt T hT x _ ha⟩

end IndependentZeroBlocks
