import Mathlib.LinearAlgebra.Matrix.ToLin
import Mathlib.RingTheory.Adjoin.FG

set_option autoImplicit false
namespace IndependentZeroBlocks
open scoped BigOperators

variable {K ι : Type*} [CommRing K] [Fintype ι]

/-- The finite set consisting of all transition entries, seed coordinates,
and scalar observation coefficients of a matrix digit recurrence. -/
noncomputable def linearObservationCoefficientGenerators
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K) (a : ι → K) :
    Finset K := by
  classical
  exact (Finset.univ.biUnion fun r ↦ Finset.univ.biUnion fun i ↦
      Finset.univ.image fun j ↦ M r i j) ∪
    (Finset.univ.image fun i ↦ u 0 i) ∪
    (Finset.univ.image a)

/-- The coefficient ring generated by a finite matrix recurrence, its seed,
and one scalar observation row. -/
noncomputable def linearObservationCoefficientSubring
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K) (a : ι → K) :
    Subring K :=
  Subring.closure (linearObservationCoefficientGenerators M u a : Set K)

instance linearObservationCoefficientSubring_noetherian
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K) (a : ι → K) :
    IsNoetherianRing (linearObservationCoefficientSubring M u a) :=
  is_noetherian_subring_closure _ (Finset.finite_toSet _)

theorem linearObservationCoefficientSubring_matrix_mem
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K) (a : ι → K)
    (r : Fin b) (i j : ι) :
    M r i j ∈ linearObservationCoefficientSubring M u a := by
  classical
  apply Subring.subset_closure
  simp only [linearObservationCoefficientGenerators, Finset.mem_coe,
    Finset.mem_union, Finset.mem_biUnion, Finset.mem_univ, true_and,
    Finset.mem_image]
  exact Or.inl (Or.inl ⟨r, i, j, rfl⟩)

theorem linearObservationCoefficientSubring_seed_mem
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K) (a : ι → K)
    (i : ι) : u 0 i ∈ linearObservationCoefficientSubring M u a := by
  classical
  apply Subring.subset_closure
  simp only [linearObservationCoefficientGenerators, Finset.mem_coe,
    Finset.mem_union, Finset.mem_biUnion, Finset.mem_univ, true_and,
    Finset.mem_image]
  exact Or.inl (Or.inr ⟨i, rfl⟩)

theorem linearObservationCoefficientSubring_row_mem
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K) (a : ι → K)
    (i : ι) : a i ∈ linearObservationCoefficientSubring M u a := by
  classical
  apply Subring.subset_closure
  simp only [linearObservationCoefficientGenerators, Finset.mem_coe,
    Finset.mem_union, Finset.mem_biUnion, Finset.mem_univ, true_and,
    Finset.mem_image]
  exact Or.inr ⟨i, rfl⟩

/-- Every state coordinate remains in the subring generated by the finite
transition data and the initial state. -/
theorem linearObservationCoefficientSubring_state_mem
    (b : ℕ) (hb : 2 ≤ b) (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K)
    (a : ι → K)
    (hrec : ∀ n (r : Fin b),
      u (b * n + r.val) = Matrix.mulVecLin (M r) (u n))
    (n : ℕ) (i : ι) :
    u n i ∈ linearObservationCoefficientSubring M u a := by
  classical
  induction n using Nat.strong_induction_on generalizing i with
  | h n ih =>
      by_cases hn : n = 0
      · subst n
        exact linearObservationCoefficientSubring_seed_mem M u a i
      · let r : Fin b := ⟨n % b, Nat.mod_lt n (by omega)⟩
        have hnrepr : n = b * (n / b) + r.val := by
          simpa only [r, Nat.mul_comm] using (Nat.div_add_mod n b).symm
        rw [hnrepr, hrec]
        change ∑ j, M r i j * u (n / b) j ∈
          linearObservationCoefficientSubring M u a
        apply Subring.sum_mem
        intro j hj
        apply Subring.mul_mem
        · exact linearObservationCoefficientSubring_matrix_mem M u a r i j
        · apply ih (n / b)
          exact Nat.div_lt_self (by omega) (by omega)

/-- The transition matrix descended entrywise to the generated subring. -/
noncomputable def linearObservationDescendedMatrix
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K) (a : ι → K) :
    Fin b → Matrix ι ι (linearObservationCoefficientSubring M u a) :=
  fun r i j ↦ ⟨M r i j, linearObservationCoefficientSubring_matrix_mem M u a r i j⟩

/-- The entire recurrence state descended coordinatewise to the generated
subring. -/
noncomputable def linearObservationDescendedState
    (b : ℕ) (hb : 2 ≤ b) (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K)
    (a : ι → K)
    (hrec : ∀ n (r : Fin b),
      u (b * n + r.val) = Matrix.mulVecLin (M r) (u n)) :
    ℕ → ι → linearObservationCoefficientSubring M u a :=
  fun n i ↦ ⟨u n i,
    linearObservationCoefficientSubring_state_mem b hb M u a hrec n i⟩

/-- The scalar observation row descended coordinatewise to the generated
subring. -/
noncomputable def linearObservationDescendedRow
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K) (a : ι → K) :
    ι → linearObservationCoefficientSubring M u a :=
  fun i ↦ ⟨a i, linearObservationCoefficientSubring_row_mem M u a i⟩

@[simp] theorem linearObservationDescendedMatrix_coe
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K) (a : ι → K)
    (r : Fin b) (i j : ι) :
    (linearObservationDescendedMatrix M u a r i j : K) = M r i j := rfl

@[simp] theorem linearObservationDescendedState_coe
    (b : ℕ) (hb : 2 ≤ b) (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K)
    (a : ι → K)
    (hrec : ∀ n (r : Fin b),
      u (b * n + r.val) = Matrix.mulVecLin (M r) (u n))
    (n : ℕ) (i : ι) :
    (linearObservationDescendedState b hb M u a hrec n i : K) = u n i := rfl

@[simp] theorem linearObservationDescendedRow_coe
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K) (a : ι → K)
    (i : ι) :
    (linearObservationDescendedRow M u a i : K) = a i := rfl

/-- The descended state satisfies the same matrix digit recurrence. -/
theorem linearObservationDescendedState_recurrence
    (b : ℕ) (hb : 2 ≤ b) (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K)
    (a : ι → K)
    (hrec : ∀ n (r : Fin b),
      u (b * n + r.val) = Matrix.mulVecLin (M r) (u n))
    (n : ℕ) (r : Fin b) :
    linearObservationDescendedState b hb M u a hrec (b * n + r.val) =
      Matrix.mulVecLin (linearObservationDescendedMatrix M u a r)
        (linearObservationDescendedState b hb M u a hrec n) := by
  funext i
  apply Subtype.ext
  dsimp only [linearObservationDescendedState, linearObservationDescendedMatrix,
    Matrix.mulVecLin_apply, Matrix.mulVec, dotProduct]
  push_cast
  exact congrFun (hrec n r) i

/-- Descent preserves every value of the scalar row applied to the state. -/
theorem linearObservationDescended_output
    (b : ℕ) (hb : 2 ≤ b) (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K)
    (a : ι → K)
    (hrec : ∀ n (r : Fin b),
      u (b * n + r.val) = Matrix.mulVecLin (M r) (u n))
    (n : ℕ) :
    ((∑ i, linearObservationDescendedRow M u a i *
      linearObservationDescendedState b hb M u a hrec n i :
        linearObservationCoefficientSubring M u a) : K) =
      ∑ i, a i * u n i := by
  push_cast
  rfl

/-- Every finite matrix digit recurrence and scalar row over an arbitrary
commutative ring descend to a Noetherian coefficient subring, preserving the
recurrence and all scalar output values. -/
theorem linearObservation_exists_noetherian_descent
    (b : ℕ) (hb : 2 ≤ b) (M : Fin b → Matrix ι ι K) (u : ℕ → ι → K)
    (a : ι → K)
    (hrec : ∀ n (r : Fin b),
      u (b * n + r.val) = Matrix.mulVecLin (M r) (u n)) :
    ∃ S : Subring K, IsNoetherianRing S ∧
      ∃ (M' : Fin b → Matrix ι ι S) (u' : ℕ → ι → S) (a' : ι → S),
        (∀ r i j, (M' r i j : K) = M r i j) ∧
        (∀ n i, (u' n i : K) = u n i) ∧
        (∀ i, (a' i : K) = a i) ∧
        (∀ n (r : Fin b), u' (b * n + r.val) = Matrix.mulVecLin (M' r) (u' n)) ∧
        (∀ n, ((∑ i, a' i * u' n i : S) : K) = ∑ i, a i * u n i) := by
  let S := linearObservationCoefficientSubring M u a
  let M' := linearObservationDescendedMatrix M u a
  let u' := linearObservationDescendedState b hb M u a hrec
  let a' := linearObservationDescendedRow M u a
  refine ⟨S, inferInstance, M', u', a', ?_, ?_, ?_, ?_, ?_⟩
  · exact linearObservationDescendedMatrix_coe M u a
  · exact linearObservationDescendedState_coe b hb M u a hrec
  · exact linearObservationDescendedRow_coe M u a
  · exact linearObservationDescendedState_recurrence b hb M u a hrec
  · exact linearObservationDescended_output b hb M u a hrec

end IndependentZeroBlocks
