import SierpinskiFormal.SourceFullAtomicLaw

#check IndependentZeroBlocks.FiniteStateSource.exists_commonReset_source_polynomialWord_analytic_atomic_law
#check IndependentZeroBlocks.FiniteStateSource.source_atomic_family_simultaneous
#check IndependentZeroBlocks.FiniteStateSource.source_atomicLaw_pathwise
#check IndependentZeroBlocks.FiniteStateSource.analyticAt_sourceBlockMixedMoment
#check IndependentZeroBlocks.FiniteStateSource.sourceBlockMixedMoment_eq_integral
#check IndependentZeroBlocks.FiniteStateSource.analyticAt_sourceComplexExpTransform
#check IndependentZeroBlocks.FiniteStateSource.sourceComplexExpTransform_entire
#check IndependentZeroBlocks.FiniteStateSource.sourceComplexExpTransform_eq_integral

#print axioms IndependentZeroBlocks.FiniteStateSource.exists_commonReset_source_polynomialWord_analytic_atomic_law
#print axioms IndependentZeroBlocks.FiniteStateSource.source_atomic_family_simultaneous
#print axioms IndependentZeroBlocks.FiniteStateSource.source_atomicLaw_pathwise
#print axioms IndependentZeroBlocks.FiniteStateSource.analyticAt_sourceBlockMixedMoment
#print axioms IndependentZeroBlocks.FiniteStateSource.sourceBlockMixedMoment_eq_integral
#print axioms IndependentZeroBlocks.FiniteStateSource.analyticAt_sourceComplexExpTransform
#print axioms IndependentZeroBlocks.FiniteStateSource.sourceComplexExpTransform_entire
#print axioms IndependentZeroBlocks.FiniteStateSource.sourceComplexExpTransform_eq_integral
