import SierpinskiFormal.ModuleReturnGroup
import SierpinskiFormal.NoetherianArtinianEmbedding
import SierpinskiFormal.MatrixBoundaryExpansion
import Mathlib.RingTheory.Adjoin.FG

set_option autoImplicit false

/-!
# Finite matrix observations over an Artinian coefficient target

A finite matrix alphabet, seed, and observation row over an arbitrary
commutative ring descend to their finitely generated coefficient subring.
That subring is Noetherian and therefore embeds in a faithful Artinian
target.  Injectivity preserves the Boolean support of every word scalar.
-/

noncomputable section

open scoped BigOperators

namespace IndependentZeroBlocks

variable {K A ι : Type*} [CommRing K] [Fintype A]
  [Fintype ι] [DecidableEq ι]

/-- Chronological matrix product over an arbitrary commutative ring. -/
def commRingMatrixWord (M : A → Matrix ι ι K) (w : List A) :
    Matrix ι ι K :=
  (w.map M).prod

@[simp] theorem commRingMatrixWord_nil (M : A → Matrix ι ι K) :
    commRingMatrixWord M [] = 1 := by
  simp [commRingMatrixWord]

@[simp] theorem commRingMatrixWord_append
    (M : A → Matrix ι ι K) (x y : List A) :
    commRingMatrixWord M (x ++ y) =
      commRingMatrixWord M x * commRingMatrixWord M y := by
  simp [commRingMatrixWord]

/-- Scalar row/matrix-word/seed coefficient over a commutative ring. -/
def commRingMatrixCoefficient (M : A → Matrix ι ι K)
    (left seed : ι → K) (w : List A) : K :=
  ∑ i, left i * (commRingMatrixWord M w).mulVec seed i

/-- Boolean support predicate of a commutative-ring matrix coefficient. -/
def commRingMatrixCoefficientNonzero (M : A → Matrix ι ι K)
    (left seed : ι → K) (w : List A) : Bool :=
  nonzeroBool (commRingMatrixCoefficient M left seed w)

/-- The finite set of entries appearing in the transition matrices, the
observation row, and the seed. -/
def matrixObservationCoefficientGenerators
    (M : A → Matrix ι ι K) (left seed : ι → K) : Finset K := by
  classical
  exact (Finset.univ.biUnion fun a ↦ Finset.univ.biUnion fun i ↦
      Finset.univ.image fun j ↦ M a i j) ∪
    (Finset.univ.image left ∪ Finset.univ.image seed)

/-- The subring generated by all finite matrix-observation data. -/
def matrixObservationCoefficientSubring
    (M : A → Matrix ι ι K) (left seed : ι → K) : Subring K :=
  Subring.closure (matrixObservationCoefficientGenerators M left seed : Set K)

instance matrixObservationCoefficientSubring_isNoetherianRing
    (M : A → Matrix ι ι K) (left seed : ι → K) :
    IsNoetherianRing (matrixObservationCoefficientSubring M left seed) :=
  is_noetherian_subring_closure _ (Finset.finite_toSet _)

theorem matrixObservationCoefficientSubring_matrix_mem
    (M : A → Matrix ι ι K) (left seed : ι → K)
    (a : A) (i j : ι) :
    M a i j ∈ matrixObservationCoefficientSubring M left seed := by
  classical
  apply Subring.subset_closure
  simp only [matrixObservationCoefficientGenerators, Finset.mem_coe,
    Finset.mem_union, Finset.mem_biUnion, Finset.mem_univ, true_and,
    Finset.mem_image]
  exact Or.inl ⟨a, i, j, rfl⟩

theorem matrixObservationCoefficientSubring_left_mem
    (M : A → Matrix ι ι K) (left seed : ι → K) (i : ι) :
    left i ∈ matrixObservationCoefficientSubring M left seed := by
  classical
  apply Subring.subset_closure
  simp only [matrixObservationCoefficientGenerators, Finset.mem_coe,
    Finset.mem_union, Finset.mem_biUnion, Finset.mem_univ, true_and,
    Finset.mem_image]
  exact Or.inr (Or.inl ⟨i, rfl⟩)

theorem matrixObservationCoefficientSubring_seed_mem
    (M : A → Matrix ι ι K) (left seed : ι → K) (i : ι) :
    seed i ∈ matrixObservationCoefficientSubring M left seed := by
  classical
  apply Subring.subset_closure
  simp only [matrixObservationCoefficientGenerators, Finset.mem_coe,
    Finset.mem_union, Finset.mem_biUnion, Finset.mem_univ, true_and,
    Finset.mem_image]
  exact Or.inr (Or.inr ⟨i, rfl⟩)

/-- Transition matrices with their entries restricted to the generated
coefficient subring. -/
def matrixObservationDescendedMatrix
    (M : A → Matrix ι ι K) (left seed : ι → K) :
    A → Matrix ι ι (matrixObservationCoefficientSubring M left seed) :=
  fun a i j ↦ ⟨M a i j,
    matrixObservationCoefficientSubring_matrix_mem M left seed a i j⟩

/-- Observation row restricted to the generated coefficient subring. -/
def matrixObservationDescendedLeft
    (M : A → Matrix ι ι K) (left seed : ι → K) :
    ι → matrixObservationCoefficientSubring M left seed :=
  fun i ↦ ⟨left i, matrixObservationCoefficientSubring_left_mem M left seed i⟩

/-- Seed restricted to the generated coefficient subring. -/
def matrixObservationDescendedSeed
    (M : A → Matrix ι ι K) (left seed : ι → K) :
    ι → matrixObservationCoefficientSubring M left seed :=
  fun i ↦ ⟨seed i, matrixObservationCoefficientSubring_seed_mem M left seed i⟩

@[simp] theorem matrixObservationDescendedMatrix_coe
    (M : A → Matrix ι ι K) (left seed : ι → K)
    (a : A) (i j : ι) :
    (matrixObservationDescendedMatrix M left seed a i j : K) = M a i j := rfl

@[simp] theorem matrixObservationDescendedLeft_coe
    (M : A → Matrix ι ι K) (left seed : ι → K) (i : ι) :
    (matrixObservationDescendedLeft M left seed i : K) = left i := rfl

@[simp] theorem matrixObservationDescendedSeed_coe
    (M : A → Matrix ι ι K) (left seed : ι → K) (i : ι) :
    (matrixObservationDescendedSeed M left seed i : K) = seed i := rfl

section RingMap

variable {L : Type*} [CommRing L]

/-- Ring maps commute with chronological matrix-word products. -/
theorem map_commRingMatrixWord (f : K →+* L)
    (M : A → Matrix ι ι K) (w : List A) :
    (commRingMatrixWord M w).map f =
      commRingMatrixWord (fun a ↦ (M a).map f) w := by
  induction w with
  | nil => simp
  | cons a w ih =>
      change (M a * commRingMatrixWord M w).map f =
        (M a).map f *
          commRingMatrixWord (fun a ↦ (M a).map f) w
      rw [Matrix.map_mul]
      congr 1

/-- Ring maps commute with every scalar matrix-word observation. -/
theorem map_commRingMatrixCoefficient (f : K →+* L)
    (M : A → Matrix ι ι K) (left seed : ι → K) (w : List A) :
    f (commRingMatrixCoefficient M left seed w) =
      commRingMatrixCoefficient (fun a ↦ (M a).map f)
        (fun i ↦ f (left i)) (fun i ↦ f (seed i)) w := by
  unfold commRingMatrixCoefficient
  rw [map_sum]
  apply Finset.sum_congr rfl
  intro i hi
  rw [map_mul, RingHom.map_mulVec, map_commRingMatrixWord]
  rfl

/-- An injective coefficient map preserves the Boolean support of every
matrix-word scalar. -/
theorem commRingMatrixCoefficientNonzero_map_of_injective
    (f : K →+* L) (hf : Function.Injective f)
    (M : A → Matrix ι ι K) (left seed : ι → K) (w : List A) :
    commRingMatrixCoefficientNonzero (fun a ↦ (M a).map f)
        (fun i ↦ f (left i)) (fun i ↦ f (seed i)) w =
      commRingMatrixCoefficientNonzero M left seed w := by
  unfold commRingMatrixCoefficientNonzero
  rw [← map_commRingMatrixCoefficient]
  by_cases hzero : commRingMatrixCoefficient M left seed w = 0
  · simp [nonzeroBool, hzero]
  · have hmap : f (commRingMatrixCoefficient M left seed w) ≠ 0 := by
      intro h
      apply hzero
      exact hf (by simpa using h)
    simp [nonzeroBool, hzero, hmap]

end RingMap

/-- The descended finite data reproduce every original word scalar after
coercion to the ambient ring. -/
theorem matrixObservationDescended_support
    (M : A → Matrix ι ι K) (left seed : ι → K) (w : List A) :
    commRingMatrixCoefficientNonzero
        (matrixObservationDescendedMatrix M left seed)
        (matrixObservationDescendedLeft M left seed)
        (matrixObservationDescendedSeed M left seed) w =
      commRingMatrixCoefficientNonzero M left seed w := by
  symm
  have h := commRingMatrixCoefficientNonzero_map_of_injective
    (matrixObservationCoefficientSubring M left seed).subtype
    (matrixObservationCoefficientSubring M left seed).subtype_injective
    (matrixObservationDescendedMatrix M left seed)
    (matrixObservationDescendedLeft M left seed)
    (matrixObservationDescendedSeed M left seed) w
  have hM : (fun a ↦ (matrixObservationDescendedMatrix M left seed a).map
      (matrixObservationCoefficientSubring M left seed).subtype) = M := by
    funext a i j
    rfl
  have hl : (fun i ↦ (matrixObservationCoefficientSubring M left seed).subtype
      (matrixObservationDescendedLeft M left seed i)) = left := by
    funext i
    rfl
  have hv : (fun i ↦ (matrixObservationCoefficientSubring M left seed).subtype
      (matrixObservationDescendedSeed M left seed i)) = seed := by
    funext i
    rfl
  rw [hM, hl, hv] at h
  exact h

/-- Every finite commutative-ring matrix observation descends to a
Noetherian coefficient subring, preserving all word support values. -/
theorem exists_noetherian_matrixObservation_descent
    (M : A → Matrix ι ι K) (left seed : ι → K) :
    ∃ S : Subring K, IsNoetherianRing S ∧
      ∃ (M' : A → Matrix ι ι S) (left' seed' : ι → S),
        (∀ a i j, (M' a i j : K) = M a i j) ∧
        (∀ i, (left' i : K) = left i) ∧
        (∀ i, (seed' i : K) = seed i) ∧
        ∀ w, commRingMatrixCoefficientNonzero M' left' seed' w =
          commRingMatrixCoefficientNonzero M left seed w := by
  exact ⟨matrixObservationCoefficientSubring M left seed, inferInstance,
    matrixObservationDescendedMatrix M left seed,
    matrixObservationDescendedLeft M left seed,
    matrixObservationDescendedSeed M left seed,
    matrixObservationDescendedMatrix_coe M left seed,
    matrixObservationDescendedLeft_coe M left seed,
    matrixObservationDescendedSeed_coe M left seed,
    matrixObservationDescended_support M left seed⟩

/-- Every finite matrix observation over an arbitrary commutative ring has
an Artinian realization with exactly the same Boolean word support. -/
theorem exists_artinian_matrixObservation_lift
    (M : A → Matrix ι ι K) (left seed : ι → K) :
    ∃ (S : Subring K) (T : FaithfulArtinianTarget S)
      (M' : A → Matrix ι ι T.Carrier)
      (left' seed' : ι → T.Carrier),
      IsNoetherianRing S ∧
      (∀ w, commRingMatrixCoefficientNonzero M' left' seed' w =
        commRingMatrixCoefficientNonzero M left seed w) := by
  let S := matrixObservationCoefficientSubring M left seed
  let MS : A → Matrix ι ι S := matrixObservationDescendedMatrix M left seed
  let leftS : ι → S := matrixObservationDescendedLeft M left seed
  let seedS : ι → S := matrixObservationDescendedSeed M left seed
  letI : IsNoetherianRing S := by dsimp [S]; infer_instance
  obtain ⟨T⟩ := exists_faithfulArtinianTarget S
  let MT : A → Matrix ι ι T.Carrier := fun a ↦ (MS a).map T.toRingHom
  let leftT : ι → T.Carrier := fun i ↦ T.toRingHom (leftS i)
  let seedT : ι → T.Carrier := fun i ↦ T.toRingHom (seedS i)
  refine ⟨S, T, MT, leftT, seedT, inferInstance, ?_⟩
  intro w
  calc
    commRingMatrixCoefficientNonzero MT leftT seedT w =
        commRingMatrixCoefficientNonzero MS leftS seedS w := by
      exact commRingMatrixCoefficientNonzero_map_of_injective
        T.toRingHom T.injective MS leftS seedS w
    _ = commRingMatrixCoefficientNonzero M left seed w := by
      exact matrixObservationDescended_support M left seed w

section FieldCompatibility

variable {F : Type*} [Field F]

/-- Over a field, the commutative-ring word product is the existing
`matrixWord`. -/
theorem commRingMatrixWord_eq_matrixWord
    (M : A → Matrix ι ι F) (w : List A) :
    commRingMatrixWord M w = matrixWord M w := rfl

/-- Over a field, the commutative-ring support predicate is the existing
matrix-coefficient predicate. -/
theorem commRingMatrixCoefficientNonzero_eq_matrixCoefficientNonzero
    (M : A → Matrix ι ι F) (left seed : ι → F) (w : List A) :
    commRingMatrixCoefficientNonzero M left seed w =
      matrixCoefficientNonzero M left seed w := by
  simp only [commRingMatrixCoefficientNonzero, commRingMatrixCoefficient,
    matrixCoefficientNonzero, coordinateRowDual_apply,
    commRingMatrixWord_eq_matrixWord]

/-- A finite matrix observation over a field admits an Artinian
commutative-ring realization whose Boolean word support is exactly the
original field-valued matrix-coefficient predicate. -/
theorem exists_artinian_matrixCoefficientNonzero_lift
    (M : A → Matrix ι ι F) (left seed : ι → F) :
    ∃ (S : Subring F) (T : FaithfulArtinianTarget S)
      (M' : A → Matrix ι ι T.Carrier)
      (left' seed' : ι → T.Carrier),
      IsNoetherianRing S ∧
      (∀ w, commRingMatrixCoefficientNonzero M' left' seed' w =
        matrixCoefficientNonzero M left seed w) := by
  obtain ⟨S, T, M', left', seed', hS, hsupport⟩ :=
    exists_artinian_matrixObservation_lift M left seed
  refine ⟨S, T, M', left', seed', hS, ?_⟩
  intro w
  rw [hsupport w,
    commRingMatrixCoefficientNonzero_eq_matrixCoefficientNonzero]

end FieldCompatibility

end IndependentZeroBlocks
