import SierpinskiFormal.NoetherianObservationDLP
import SierpinskiFormal.ReversibleSequenceSections
import Mathlib.LinearAlgebra.Matrix.ToLinearEquiv

/-! # The reversible group generated by minimum-rank return matrices -/

noncomputable section

open scoped BigOperators

namespace IndependentZeroBlocks

variable {F A ι : Type*} [Field F] [Fintype ι] [DecidableEq ι]

/-- An invertible return matrix, regarded as a linear automorphism of the
compressed coordinate space. -/
def returnMatrixLinearEquiv {r : ℕ}
    (M : A → Matrix ι ι F) (U : Matrix ι (Fin r) F)
    (V : Matrix (Fin r) ι F) (y : List A)
    (hy : IsUnit (returnMatrix M U V y)) :
    (Fin r → F) ≃ₗ[F] (Fin r → F) :=
  Matrix.toLinearEquiv' (returnMatrix M U V y) hy.invertible

@[simp] theorem returnMatrixLinearEquiv_apply {r : ℕ}
    (M : A → Matrix ι ι F) (U : Matrix ι (Fin r) F)
    (V : Matrix (Fin r) ι F) (y : List A)
    (hy : IsUnit (returnMatrix M U V y)) (v : Fin r → F) :
    returnMatrixLinearEquiv M U V y hy v =
      (returnMatrix M U V y).mulVec v := by
  change (Matrix.toLinearEquiv' (returnMatrix M U V y) hy.invertible :
    Module.End F (Fin r → F)) v = _
  rw [Matrix.toLinearEquiv'_apply, Matrix.toLin'_apply', Matrix.mulVecLin_apply]

/-- The free-group action whose positive generators are the actual return
matrices. The generator type is the countable alphabet of return words. -/
def returnFreeGroupLinearAction {r : ℕ}
    (M : A → Matrix ι ι F) (U : Matrix ι (Fin r) F)
    (V : Matrix (Fin r) ι F)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y)) :
    FreeGroup (List A) →* ((Fin r → F) ≃ₗ[F] (Fin r → F)) :=
  freeGroupLinearAction (fun y ↦ returnMatrixLinearEquiv M U V y (hunit y))

@[simp] theorem returnFreeGroupLinearAction_of_apply {r : ℕ}
    (M : A → Matrix ι ι F) (U : Matrix ι (Fin r) F)
    (V : Matrix (Fin r) ι F)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y))
    (y : List A) (v : Fin r → F) :
    returnFreeGroupLinearAction M U V hunit (FreeGroup.of y) v =
      (returnMatrix M U V y).mulVec v := by
  rw [returnFreeGroupLinearAction, freeGroupLinearAction_of,
    returnMatrixLinearEquiv_apply]

/-- A positive free word evaluates to the chronological product of its
actual return matrices. -/
theorem returnFreeGroupLinearAction_positiveWord {r : ℕ}
    (M : A → Matrix ι ι F) (U : Matrix ι (Fin r) F)
    (V : Matrix (Fin r) ι F)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y))
    (ys : List (List A)) (v : Fin r → F) :
    returnFreeGroupLinearAction M U V hunit (positiveFreeGroupWord ys) v =
      ((ys.map (returnMatrix M U V)).prod).mulVec v := by
  induction ys with
  | nil => simp [positiveFreeGroupWord]
  | cons y ys ih =>
      have ih' :
          returnFreeGroupLinearAction M U V hunit
              ((ys.map FreeGroup.of).prod) v =
            ((ys.map (returnMatrix M U V)).prod).mulVec v := by
        simpa [positiveFreeGroupWord] using ih
      simp only [positiveFreeGroupWord, List.map_cons, List.prod_cons, map_mul,
        MonoidHom.coe_mk, OneHom.coe_mk, LinearEquiv.mul_apply]
      rw [returnFreeGroupLinearAction_of_apply, ih', Matrix.mulVec_mulVec]

/-- Forget the inverses in the free-group action to obtain the endomorphism
representation expected by the Noetherian observation theorem. -/
def returnFreeGroupEndRepresentation {r : ℕ}
    (M : A → Matrix ι ι F) (U : Matrix ι (Fin r) F)
    (V : Matrix (Fin r) ι F)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y)) :
    FreeGroup (List A) →* Module.End F (Fin r → F) where
  toFun γ := (returnFreeGroupLinearAction M U V hunit γ).toLinearMap
  map_one' := by
    apply LinearMap.ext
    intro v
    change returnFreeGroupLinearAction M U V hunit 1 v = v
    simp
  map_mul' γ δ := by
    apply LinearMap.ext
    intro v
    change returnFreeGroupLinearAction M U V hunit (γ * δ) v =
      returnFreeGroupLinearAction M U V hunit γ
        (returnFreeGroupLinearAction M U V hunit δ v)
    rw [map_mul, LinearEquiv.mul_apply]

/-- Scalar coefficient of the return-group representation with fixed
compressed boundary vectors. -/
def returnGroupScalarPredicate {r : ℕ}
    (M : A → Matrix ι ι F) (U : Matrix ι (Fin r) F)
    (V : Matrix (Fin r) ι F)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y))
    (left : Module.Dual F (Fin r → F)) (seed : Fin r → F)
    (γ : FreeGroup (List A)) : Bool :=
  nonzeroBool (left (returnFreeGroupLinearAction M U V hunit γ seed))

/-- The return-group scalar predicate is stable, with no finiteness
assumption on its return-word generator alphabet. -/
theorem returnGroupScalarPredicate_hasBooleanDoubleLimitProperty {r : ℕ}
    (M : A → Matrix ι ι F) (U : Matrix ι (Fin r) F)
    (V : Matrix (Fin r) ι F)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y))
    (left : Module.Dual F (Fin r → F)) (seed : Fin r → F) :
    HasBooleanDoubleLimitProperty
      (booleanGroupRightRow
        (returnGroupScalarPredicate M U V hunit left seed)) := by
  change HasBooleanDoubleLimitProperty (fun g h ↦ nonzeroBool
    (left (returnFreeGroupLinearAction M U V hunit (h * g) seed)))
  have H := noetherian_groupObservation_rightRow_hasBooleanDoubleLimitProperty
    (returnFreeGroupEndRepresentation M U V hunit) left seed
  have H' : HasBooleanDoubleLimitProperty (fun g h ↦ nonzeroBool
      (left ((returnFreeGroupEndRepresentation M U V hunit h)
        ((returnFreeGroupEndRepresentation M U V hunit g) seed)))) := by
    simpa only [map_mul, Module.End.mul_apply] using H
  have hrep (g : FreeGroup (List A)) (v : Fin r → F) :
      returnFreeGroupEndRepresentation M U V hunit g v =
        returnFreeGroupLinearAction M U V hunit g v := rfl
  simpa only [map_mul, LinearEquiv.mul_apply, hrep] using H'

/-- The left boundary of a reset sandwich, compressed to the return space. -/
def returnBoundaryDual {r : ℕ} (M : A → Matrix ι ι F) (x : List A)
    (U : Matrix ι (Fin r) F) (lambda : ι → F) :
    Module.Dual F (Fin r → F) :=
  (coordinateRowDual lambda).comp (matrixWord M x * U).mulVecLin

/-- The right boundary of a reset sandwich, compressed to the return space. -/
def returnBoundarySeed {r : ℕ} (M : A → Matrix ι ι F) (z : List A)
    (V : Matrix (Fin r) ι F) (gamma : ι → F) : Fin r → F :=
  (V * matrixWord M z).mulVec gamma

/-- Positive return-group words evaluate the original matrix coefficient
between fixed boundary words. -/
theorem returnGroupScalar_positiveWord_eq_boundary_resetSandwich {r : ℕ}
    (M : A → Matrix ι ι F) (h x z : List A)
    (U : Matrix ι (Fin r) F) (V : Matrix (Fin r) ι F)
    (hfac : matrixWord M h = U * V)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y))
    (ys : List (List A)) (lambda gamma : ι → F) :
    returnBoundaryDual M x U lambda
        (returnFreeGroupLinearAction M U V hunit
          (positiveFreeGroupWord ys) (returnBoundarySeed M z V gamma)) =
      coordinateRowDual lambda
        ((matrixWord M (x ++ resetSandwichWord h ys ++ z)).mulVec gamma) := by
  rw [returnFreeGroupLinearAction_positiveWord]
  unfold returnBoundaryDual returnBoundarySeed
  simp only [LinearMap.comp_apply, Matrix.mulVecLin_apply]
  exact (coefficient_boundary_resetSandwichWord
    M h x z U V hfac ys lambda gamma).symm

/-- Boolean form of the positive-word boundary evaluation. -/
theorem returnGroupScalarPredicate_positiveWord {r : ℕ}
    (M : A → Matrix ι ι F) (h x z : List A)
    (U : Matrix ι (Fin r) F) (V : Matrix (Fin r) ι F)
    (hfac : matrixWord M h = U * V)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y))
    (ys : List (List A)) (lambda gamma : ι → F) :
    returnGroupScalarPredicate M U V hunit
        (returnBoundaryDual M x U lambda) (returnBoundarySeed M z V gamma)
        (positiveFreeGroupWord ys) =
      nonzeroBool (coordinateRowDual lambda
        ((matrixWord M (x ++ resetSandwichWord h ys ++ z)).mulVec gamma)) := by
  exact congrArg nonzeroBool
    (returnGroupScalar_positiveWord_eq_boundary_resetSandwich
      M h x z U V hfac hunit ys lambda gamma)

section EncodedReturnAlphabet

variable {D : Type*}

/-- Return action indexed by the exact support alphabet `D`.  The encoding
may select marker-free words, so no zero-weight generators are introduced. -/
def encodedReturnFreeGroupLinearAction {r : ℕ}
    (M : A → Matrix ι ι F) (U : Matrix ι (Fin r) F)
    (V : Matrix (Fin r) ι F)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y))
    (encode : D → List A) :
    FreeGroup D →* ((Fin r → F) ≃ₗ[F] (Fin r → F)) :=
  freeGroupLinearAction (fun d ↦
    returnMatrixLinearEquiv M U V (encode d) (hunit (encode d)))

@[simp] theorem encodedReturnFreeGroupLinearAction_of_apply {r : ℕ}
    (M : A → Matrix ι ι F) (U : Matrix ι (Fin r) F)
    (V : Matrix (Fin r) ι F)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y))
    (encode : D → List A) (d : D) (v : Fin r → F) :
    encodedReturnFreeGroupLinearAction M U V hunit encode (FreeGroup.of d) v =
      (returnMatrix M U V (encode d)).mulVec v := by
  rw [encodedReturnFreeGroupLinearAction, freeGroupLinearAction_of,
    returnMatrixLinearEquiv_apply]

/-- A positive word in the exact support alphabet evaluates to the product
of the corresponding encoded return matrices. -/
theorem encodedReturnFreeGroupLinearAction_positiveWord {r : ℕ}
    (M : A → Matrix ι ι F) (U : Matrix ι (Fin r) F)
    (V : Matrix (Fin r) ι F)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y))
    (encode : D → List A) (ds : List D) (v : Fin r → F) :
    encodedReturnFreeGroupLinearAction M U V hunit encode
        (positiveFreeGroupWord ds) v =
      ((ds.map (fun d ↦ returnMatrix M U V (encode d))).prod).mulVec v := by
  induction ds with
  | nil => simp [positiveFreeGroupWord]
  | cons d ds ih =>
      have ih' :
          encodedReturnFreeGroupLinearAction M U V hunit encode
              ((ds.map FreeGroup.of).prod) v =
            ((ds.map (fun d ↦ returnMatrix M U V (encode d))).prod).mulVec v := by
        simpa [positiveFreeGroupWord] using ih
      simp only [positiveFreeGroupWord, List.map_cons, List.prod_cons, map_mul,
        MonoidHom.coe_mk, OneHom.coe_mk, LinearEquiv.mul_apply]
      rw [encodedReturnFreeGroupLinearAction_of_apply, ih', Matrix.mulVec_mulVec]

/-- The exact-support free-group action, regarded as an endomorphism
representation for the Noetherian observation theorem. -/
def encodedReturnFreeGroupEndRepresentation {r : ℕ}
    (M : A → Matrix ι ι F) (U : Matrix ι (Fin r) F)
    (V : Matrix (Fin r) ι F)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y))
    (encode : D → List A) :
    FreeGroup D →* Module.End F (Fin r → F) where
  toFun γ := (encodedReturnFreeGroupLinearAction M U V hunit encode γ).toLinearMap
  map_one' := by
    apply LinearMap.ext
    intro v
    change encodedReturnFreeGroupLinearAction M U V hunit encode 1 v = v
    simp
  map_mul' γ δ := by
    apply LinearMap.ext
    intro v
    change encodedReturnFreeGroupLinearAction M U V hunit encode (γ * δ) v =
      encodedReturnFreeGroupLinearAction M U V hunit encode γ
        (encodedReturnFreeGroupLinearAction M U V hunit encode δ v)
    rw [map_mul, LinearEquiv.mul_apply]

/-- Boolean scalar predicate for the exact support free group. -/
def encodedReturnGroupScalarPredicate {r : ℕ}
    (M : A → Matrix ι ι F) (U : Matrix ι (Fin r) F)
    (V : Matrix (Fin r) ι F)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y))
    (encode : D → List A)
    (left : Module.Dual F (Fin r → F)) (seed : Fin r → F)
    (γ : FreeGroup D) : Bool :=
  nonzeroBool
    (left (encodedReturnFreeGroupLinearAction M U V hunit encode γ seed))

/-- Exact-support return-group scalar predicates are stable, with no
finiteness assumption on `D`. -/
theorem encodedReturnGroupScalarPredicate_hasBooleanDoubleLimitProperty {r : ℕ}
    (M : A → Matrix ι ι F) (U : Matrix ι (Fin r) F)
    (V : Matrix (Fin r) ι F)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y))
    (encode : D → List A)
    (left : Module.Dual F (Fin r → F)) (seed : Fin r → F) :
    HasBooleanDoubleLimitProperty
      (booleanGroupRightRow
        (encodedReturnGroupScalarPredicate M U V hunit encode left seed)) := by
  change HasBooleanDoubleLimitProperty (fun g h ↦ nonzeroBool
    (left (encodedReturnFreeGroupLinearAction M U V hunit encode (h * g) seed)))
  have H := noetherian_groupObservation_rightRow_hasBooleanDoubleLimitProperty
    (encodedReturnFreeGroupEndRepresentation M U V hunit encode) left seed
  have H' : HasBooleanDoubleLimitProperty (fun g h ↦ nonzeroBool
      (left ((encodedReturnFreeGroupEndRepresentation M U V hunit encode h)
        ((encodedReturnFreeGroupEndRepresentation M U V hunit encode g) seed)))) := by
    simpa only [map_mul, Module.End.mul_apply] using H
  have hrep (g : FreeGroup D) (v : Fin r → F) :
      encodedReturnFreeGroupEndRepresentation M U V hunit encode g v =
        encodedReturnFreeGroupLinearAction M U V hunit encode g v := rfl
  simpa only [map_mul, LinearEquiv.mul_apply, hrep] using H'

/-- Exact-support positive words evaluate the original matrix coefficient
with the encoded words inserted between reset blocks. -/
theorem encodedReturnGroupScalar_positiveWord_eq_boundary_resetSandwich {r : ℕ}
    (M : A → Matrix ι ι F) (h x z : List A)
    (U : Matrix ι (Fin r) F) (V : Matrix (Fin r) ι F)
    (hfac : matrixWord M h = U * V)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y))
    (encode : D → List A) (ds : List D) (lambda gamma : ι → F) :
    returnBoundaryDual M x U lambda
        (encodedReturnFreeGroupLinearAction M U V hunit encode
          (positiveFreeGroupWord ds) (returnBoundarySeed M z V gamma)) =
      coordinateRowDual lambda
        ((matrixWord M
          (x ++ resetSandwichWord h (ds.map encode) ++ z)).mulVec gamma) := by
  rw [encodedReturnFreeGroupLinearAction_positiveWord]
  unfold returnBoundaryDual returnBoundarySeed
  simp only [LinearMap.comp_apply, Matrix.mulVecLin_apply]
  have hmap : ds.map (fun d ↦ returnMatrix M U V (encode d)) =
      (ds.map encode).map (returnMatrix M U V) := by
    induction ds with
    | nil => rfl
    | cons d ds ih =>
        simp only [List.map_cons]
        rw [ih]
  rw [hmap]
  exact (coefficient_boundary_resetSandwichWord
    M h x z U V hfac (ds.map encode) lambda gamma).symm

/-- Boolean form of exact-support positive-word boundary evaluation. -/
theorem encodedReturnGroupScalarPredicate_positiveWord {r : ℕ}
    (M : A → Matrix ι ι F) (h x z : List A)
    (U : Matrix ι (Fin r) F) (V : Matrix (Fin r) ι F)
    (hfac : matrixWord M h = U * V)
    (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y))
    (encode : D → List A) (ds : List D) (lambda gamma : ι → F) :
    encodedReturnGroupScalarPredicate M U V hunit encode
        (returnBoundaryDual M x U lambda) (returnBoundarySeed M z V gamma)
        (positiveFreeGroupWord ds) =
      nonzeroBool (coordinateRowDual lambda
        ((matrixWord M
          (x ++ resetSandwichWord h (ds.map encode) ++ z)).mulVec gamma)) := by
  exact congrArg nonzeroBool
    (encodedReturnGroupScalar_positiveWord_eq_boundary_resetSandwich
      M h x z U V hfac hunit encode ds lambda gamma)

/-- The canonical exact-support generators generate the whole free group.
If `D` is countable, so is that free group. -/
theorem encodedReturnFreeGroup_countable_and_generated
    (D : Type*) [Countable D] :
    Countable (FreeGroup D) ∧
      Subgroup.closure (Set.range (FreeGroup.of : D → FreeGroup D)) = ⊤ := by
  exact ⟨by infer_instance, freeGroup_closure_range_of_eq_top D⟩

/-- An injective encoding into a countable word alphabet supplies the
countability instance needed by the exact-support group law.  In particular,
this applies to the subtype inclusion of marker-free gap words. -/
theorem encodedReturnFreeGroup_countable_and_generated_of_injective
    (encode : D → List A) (hencode : Function.Injective encode)
    [Countable (List A)] :
    Countable (FreeGroup D) ∧
      Subgroup.closure (Set.range (FreeGroup.of : D → FreeGroup D)) = ⊤ := by
  letI : Countable D := hencode.countable
  exact encodedReturnFreeGroup_countable_and_generated D

end EncodedReturnAlphabet

/-- Minimum rank alone produces an actual reversible return representation
and its stable scalar predicates; invertibility is a conclusion, not an
extra hypothesis. -/
theorem exists_stable_returnFreeGroupAction_of_minRank
    (M : A → Matrix ι ι F) (h : List A) (hh : h ≠ [])
    (hmin : ∀ w : List A, w ≠ [] →
      (matrixWord M h).rank ≤ (matrixWord M w).rank) :
    ∃ (U : Matrix ι (Fin (matrixWord M h).rank) F)
      (V : Matrix (Fin (matrixWord M h).rank) ι F)
      (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y)),
      matrixWord M h = U * V ∧
      (∀ y v, returnFreeGroupLinearAction M U V hunit (FreeGroup.of y) v =
        (returnMatrix M U V y).mulVec v) ∧
      ∀ (left : Module.Dual F (Fin (matrixWord M h).rank → F)) seed,
        HasBooleanDoubleLimitProperty
          (booleanGroupRightRow
            (returnGroupScalarPredicate M U V hunit left seed)) := by
  obtain ⟨U, V, hfac, hunit⟩ := exists_minRankCompression M h hh hmin
  exact ⟨U, V, hunit, hfac,
    returnFreeGroupLinearAction_of_apply M U V hunit,
    returnGroupScalarPredicate_hasBooleanDoubleLimitProperty M U V hunit⟩

/-- Minimum rank also produces the reversible stable action on any exact
support alphabet `D`, through an encoding of support elements as words. -/
theorem exists_stable_encodedReturnFreeGroupAction_of_minRank
    {D : Type*} (M : A → Matrix ι ι F) (h : List A) (hh : h ≠ [])
    (hmin : ∀ w : List A, w ≠ [] →
      (matrixWord M h).rank ≤ (matrixWord M w).rank)
    (encode : D → List A) :
    ∃ (U : Matrix ι (Fin (matrixWord M h).rank) F)
      (V : Matrix (Fin (matrixWord M h).rank) ι F)
      (hunit : ∀ y : List A, IsUnit (returnMatrix M U V y)),
      matrixWord M h = U * V ∧
      (∀ d v,
        encodedReturnFreeGroupLinearAction M U V hunit encode (FreeGroup.of d) v =
          (returnMatrix M U V (encode d)).mulVec v) ∧
      ∀ (left : Module.Dual F (Fin (matrixWord M h).rank → F)) seed,
        HasBooleanDoubleLimitProperty
          (booleanGroupRightRow
            (encodedReturnGroupScalarPredicate
              M U V hunit encode left seed)) := by
  obtain ⟨U, V, hfac, hunit⟩ := exists_minRankCompression M h hh hmin
  exact ⟨U, V, hunit, hfac,
    encodedReturnFreeGroupLinearAction_of_apply M U V hunit encode,
    encodedReturnGroupScalarPredicate_hasBooleanDoubleLimitProperty
      M U V hunit encode⟩

/-- For a finite underlying alphabet, the return-word free group is
countable and its canonical generators generate the whole group. -/
theorem returnFreeGroup_countable_and_generated (A : Type*) [Fintype A] :
    Countable (FreeGroup (List A)) ∧
      Subgroup.closure
        (Set.range (FreeGroup.of : List A → FreeGroup (List A))) = ⊤ := by
  exact ⟨by infer_instance, freeGroup_closure_range_of_eq_top (List A)⟩

end IndependentZeroBlocks
