import SierpinskiFormal.ArtinianCoefficientDescent
import SierpinskiFormal.ModuleBoundaryExpansion

set_option autoImplicit false

/-!
# One Artinian module realization for a finite matrix family

A finite family of matrix-word observations over an arbitrary commutative
ring is descended through one common finitely generated coefficient subring.
After its faithful embedding in an Artinian ring, the family acts
coordinatewise on one finite free module.  The original family seeds become
one common module seed, and each original observation row becomes one row on
the common module.  Every scalar nonzero test is preserved at every word.
-/

noncomputable section

open scoped BigOperators

namespace IndependentZeroBlocks

variable {R A J ι : Type*} [CommRing R] [Fintype A]
  [Fintype J] [Fintype ι] [DecidableEq ι]

/-- The entries of every matrix, row, and seed in a finite family. -/
def matrixFamilyCoefficientGenerators
    (M : J → A → Matrix ι ι R) (left seed : J → ι → R) : Finset R := by
  classical
  exact Finset.univ.biUnion fun j ↦
    matrixObservationCoefficientGenerators (M j) (left j) (seed j)

/-- The single coefficient subring generated by all data in a finite family. -/
def matrixFamilyCoefficientSubring
    (M : J → A → Matrix ι ι R) (left seed : J → ι → R) : Subring R :=
  Subring.closure (matrixFamilyCoefficientGenerators M left seed : Set R)

instance matrixFamilyCoefficientSubring_isNoetherianRing
    (M : J → A → Matrix ι ι R) (left seed : J → ι → R) :
    IsNoetherianRing (matrixFamilyCoefficientSubring M left seed) :=
  is_noetherian_subring_closure _ (Finset.finite_toSet _)

omit [DecidableEq ι] in
theorem matrixFamilyCoefficientSubring_matrix_mem
    (M : J → A → Matrix ι ι R) (left seed : J → ι → R)
    (j : J) (a : A) (i k : ι) :
    M j a i k ∈ matrixFamilyCoefficientSubring M left seed := by
  classical
  apply Subring.subset_closure
  simp only [matrixFamilyCoefficientGenerators, Finset.mem_coe,
    Finset.mem_biUnion, Finset.mem_univ, true_and]
  exact ⟨j, by
    simp only [matrixObservationCoefficientGenerators, Finset.mem_union,
      Finset.mem_biUnion, Finset.mem_univ, true_and, Finset.mem_image]
    exact Or.inl ⟨a, i, k, rfl⟩⟩

omit [DecidableEq ι] in
theorem matrixFamilyCoefficientSubring_left_mem
    (M : J → A → Matrix ι ι R) (left seed : J → ι → R)
    (j : J) (i : ι) :
    left j i ∈ matrixFamilyCoefficientSubring M left seed := by
  classical
  apply Subring.subset_closure
  simp only [matrixFamilyCoefficientGenerators, Finset.mem_coe,
    Finset.mem_biUnion, Finset.mem_univ, true_and]
  exact ⟨j, by
    simp only [matrixObservationCoefficientGenerators, Finset.mem_union,
      Finset.mem_biUnion, Finset.mem_univ, true_and, Finset.mem_image]
    exact Or.inr (Or.inl ⟨i, rfl⟩)⟩

omit [DecidableEq ι] in
theorem matrixFamilyCoefficientSubring_seed_mem
    (M : J → A → Matrix ι ι R) (left seed : J → ι → R)
    (j : J) (i : ι) :
    seed j i ∈ matrixFamilyCoefficientSubring M left seed := by
  classical
  apply Subring.subset_closure
  simp only [matrixFamilyCoefficientGenerators, Finset.mem_coe,
    Finset.mem_biUnion, Finset.mem_univ, true_and]
  exact ⟨j, by
    simp only [matrixObservationCoefficientGenerators, Finset.mem_union,
      Finset.mem_biUnion, Finset.mem_univ, true_and, Finset.mem_image]
    exact Or.inr (Or.inr ⟨i, rfl⟩)⟩

/-- All family matrices restricted to the common coefficient subring. -/
def matrixFamilyDescendedMatrix
    (M : J → A → Matrix ι ι R) (left seed : J → ι → R) :
    J → A → Matrix ι ι (matrixFamilyCoefficientSubring M left seed) :=
  fun j a i k ↦ ⟨M j a i k,
    matrixFamilyCoefficientSubring_matrix_mem M left seed j a i k⟩

/-- All family rows restricted to the common coefficient subring. -/
def matrixFamilyDescendedLeft
    (M : J → A → Matrix ι ι R) (left seed : J → ι → R) :
    J → ι → matrixFamilyCoefficientSubring M left seed :=
  fun j i ↦ ⟨left j i, matrixFamilyCoefficientSubring_left_mem M left seed j i⟩

/-- All family seeds restricted to the common coefficient subring. -/
def matrixFamilyDescendedSeed
    (M : J → A → Matrix ι ι R) (left seed : J → ι → R) :
    J → ι → matrixFamilyCoefficientSubring M left seed :=
  fun j i ↦ ⟨seed j i, matrixFamilyCoefficientSubring_seed_mem M left seed j i⟩

omit [DecidableEq ι] in
@[simp] theorem matrixFamilyDescendedMatrix_coe
    (M : J → A → Matrix ι ι R) (left seed : J → ι → R)
    (j : J) (a : A) (i k : ι) :
    (matrixFamilyDescendedMatrix M left seed j a i k : R) = M j a i k := rfl

omit [DecidableEq ι] in
@[simp] theorem matrixFamilyDescendedLeft_coe
    (M : J → A → Matrix ι ι R) (left seed : J → ι → R)
    (j : J) (i : ι) :
    (matrixFamilyDescendedLeft M left seed j i : R) = left j i := rfl

omit [DecidableEq ι] in
@[simp] theorem matrixFamilyDescendedSeed_coe
    (M : J → A → Matrix ι ι R) (left seed : J → ι → R)
    (j : J) (i : ι) :
    (matrixFamilyDescendedSeed M left seed j i : R) = seed j i := rfl

/-- One endomorphism action on the product state space, acting independently
on each family coordinate. -/
def matrixFamilyEnd {K : Type*} [CommRing K]
    (M : J → A → Matrix ι ι K) (a : A) :
    Module.End K (J → ι → K) where
  toFun x j := (M j a).mulVec (x j)
  map_add' x y := by
    funext j
    exact (M j a).mulVecLin.map_add (x j) (y j)
  map_smul' c x := by
    funext j
    exact (M j a).mulVecLin.map_smul c (x j)

/-- A family row regarded as a row on the common product state. -/
def matrixFamilyRow {K : Type*} [CommRing K]
    (left : J → ι → K) (j : J) : Module.Dual K (J → ι → K) where
  toFun x := ∑ i, left j i * x j i
  map_add' x y := by simp [mul_add, Finset.sum_add_distrib]
  map_smul' c x := by simp [Finset.mul_sum, mul_left_comm]

omit [Fintype J] [DecidableEq ι] in
@[simp] theorem matrixFamilyRow_apply {K : Type*} [CommRing K]
    (left : J → ι → K) (j : J) (x : J → ι → K) :
    matrixFamilyRow left j x = ∑ i, left j i * x j i := rfl

omit [Fintype J] in
/-- Word evaluation of the product action is coordinatewise matrix-word
evaluation. -/
theorem matrixFamilyEnd_endoWord_apply {K : Type*} [CommRing K]
    (M : J → A → Matrix ι ι K) (w : List A)
    (x : J → ι → K) (j : J) :
    endoWord (matrixFamilyEnd M) w x j =
      (commRingMatrixWord (M j) w).mulVec (x j) := by
  induction w with
  | nil => simp
  | cons a w ih =>
      rw [endoWord_cons, Module.End.mul_apply]
      change (M j a).mulVec ((endoWord (matrixFamilyEnd M) w) x j) = _
      rw [ih]
      simp only [commRingMatrixWord, List.map_cons, List.prod_cons]
      rw [Matrix.mulVec_mulVec]

omit [Fintype J] in
/-- Each row of the common action exactly evaluates its original matrix
coefficient, before taking Boolean support. -/
theorem matrixFamilyRow_endoWord_seed {K : Type*} [CommRing K]
    (M : J → A → Matrix ι ι K) (left seed : J → ι → K)
    (j : J) (w : List A) :
    matrixFamilyRow left j (endoWord (matrixFamilyEnd M) w seed) =
      commRingMatrixCoefficient (M j) (left j) (seed j) w := by
  rw [matrixFamilyRow_apply]
  simp only [matrixFamilyEnd_endoWord_apply]
  rfl

/-- One finite free Artinian module action realizes every member of a finite
matrix family, with one common seed and one selectable row per member.  The
construction allows empty family and state types and also the zero ring. -/
theorem exists_matrixFamily_faithfulArtinian_realization
    (M : J → A → Matrix ι ι R) (left seed : J → ι → R) :
    ∃ (S : Subring R) (Q : FaithfulArtinianTarget S)
      (T : A → Module.End Q.Carrier (J → ι → Q.Carrier))
      (v : J → ι → Q.Carrier)
      (rows : J → Module.Dual Q.Carrier (J → ι → Q.Carrier)),
      IsNoetherianRing S ∧
      IsArtinian Q.Carrier (J → ι → Q.Carrier) ∧
      Module.Finite Q.Carrier (J → ι → Q.Carrier) ∧
      Module.Free Q.Carrier (J → ι → Q.Carrier) ∧
      ∀ j w, moduleCoefficientNonzero T (rows j) v w =
        commRingMatrixCoefficientNonzero (M j) (left j) (seed j) w := by
  let S := matrixFamilyCoefficientSubring M left seed
  let MS : J → A → Matrix ι ι S := matrixFamilyDescendedMatrix M left seed
  let leftS : J → ι → S := matrixFamilyDescendedLeft M left seed
  let seedS : J → ι → S := matrixFamilyDescendedSeed M left seed
  letI : IsNoetherianRing S := by dsimp [S]; infer_instance
  obtain ⟨Q⟩ := exists_faithfulArtinianTarget S
  let MQ : J → A → Matrix ι ι Q.Carrier :=
    fun j a ↦ (MS j a).map Q.toRingHom
  let leftQ : J → ι → Q.Carrier := fun j i ↦ Q.toRingHom (leftS j i)
  let seedQ : J → ι → Q.Carrier := fun j i ↦ Q.toRingHom (seedS j i)
  let T : A → Module.End Q.Carrier (J → ι → Q.Carrier) := matrixFamilyEnd MQ
  let rows : J → Module.Dual Q.Carrier (J → ι → Q.Carrier) :=
    matrixFamilyRow leftQ
  refine ⟨S, Q, T, seedQ, rows, inferInstance, inferInstance,
    inferInstance, inferInstance, ?_⟩
  intro j w
  have hS : commRingMatrixCoefficientNonzero (MS j) (leftS j) (seedS j) w =
      commRingMatrixCoefficientNonzero (M j) (left j) (seed j) w := by
    have h := commRingMatrixCoefficientNonzero_map_of_injective
      S.subtype S.subtype_injective (MS j) (leftS j) (seedS j) w
    have hM : (fun a ↦ (MS j a).map S.subtype) = M j := by
      funext a i k
      rfl
    have hl : (fun i ↦ S.subtype (leftS j i)) = left j := by
      funext i
      rfl
    have hv : (fun i ↦ S.subtype (seedS j i)) = seed j := by
      funext i
      rfl
    rw [hM, hl, hv] at h
    exact h.symm
  have hQ : commRingMatrixCoefficientNonzero (MQ j) (leftQ j) (seedQ j) w =
      commRingMatrixCoefficientNonzero (MS j) (leftS j) (seedS j) w := by
    exact commRingMatrixCoefficientNonzero_map_of_injective
      Q.toRingHom Q.injective (MS j) (leftS j) (seedS j) w
  unfold moduleCoefficientNonzero
  rw [show rows j (endoWord T w seedQ) =
      commRingMatrixCoefficient (MQ j) (leftQ j) (seedQ j) w by
    exact matrixFamilyRow_endoWord_seed MQ leftQ seedQ j w]
  exact hQ.trans hS

/-- `Fin d` specialization matching the finite Boolean module interfaces. -/
theorem exists_finMatrixFamily_faithfulArtinian_realization {d : ℕ}
    (M : Fin d → A → Matrix ι ι R)
    (left seed : Fin d → ι → R) :
    ∃ (S : Subring R) (Q : FaithfulArtinianTarget S)
      (T : A → Module.End Q.Carrier (Fin d → ι → Q.Carrier))
      (v : Fin d → ι → Q.Carrier)
      (rows : Fin d →
        Module.Dual Q.Carrier (Fin d → ι → Q.Carrier)),
      IsNoetherianRing S ∧
      IsArtinian Q.Carrier (Fin d → ι → Q.Carrier) ∧
      Module.Finite Q.Carrier (Fin d → ι → Q.Carrier) ∧
      Module.Free Q.Carrier (Fin d → ι → Q.Carrier) ∧
      ∀ j w, moduleCoefficientNonzero T (rows j) v w =
        commRingMatrixCoefficientNonzero (M j) (left j) (seed j) w :=
  exists_matrixFamily_faithfulArtinian_realization M left seed

end IndependentZeroBlocks
