import SierpinskiFormal.MatrixSparseGeometry
import Mathlib.RingTheory.Adjoin.FG

set_option autoImplicit false
namespace IndependentZeroBlocks
open SierpinskiFormal
open scoped BigOperators

variable {K ι : Type*} [CommRing K] [Fintype ι]

/-- The finite coefficient data of a polynomial matrix system. -/
noncomputable def matrixCoefficientGenerators
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K) : Finset K := by
  classical
  exact (Finset.univ.image fun i => PowerSeries.coeff 0 (U i)) ∪
    Finset.univ.biUnion (fun i => Finset.univ.biUnion (fun j =>
      (Finset.range ((B i j).natDegree + 1)).image fun n => (B i j).coeff n))

noncomputable def matrixCoefficientSubring
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K) : Subring K :=
  Subring.closure (matrixCoefficientGenerators B U : Set K)

instance matrixCoefficientSubring_noetherian
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K) :
    IsNoetherianRing (matrixCoefficientSubring B U) :=
  is_noetherian_subring_closure _ (Finset.finite_toSet _)

theorem matrixCoefficientSubring_initial_mem
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K) (i : ι) :
    PowerSeries.coeff 0 (U i) ∈ matrixCoefficientSubring B U := by
  classical
  apply Subring.subset_closure
  simp only [matrixCoefficientGenerators, Finset.mem_coe, Finset.mem_union]
  exact Or.inl (Finset.mem_image.mpr ⟨i, Finset.mem_univ _, rfl⟩)

theorem matrixCoefficientSubring_polynomial_mem
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K) (i j : ι) (n : ℕ) :
    (B i j).coeff n ∈ matrixCoefficientSubring B U := by
  classical
  by_cases hn : n ≤ (B i j).natDegree
  · apply Subring.subset_closure
    simp only [matrixCoefficientGenerators, Finset.mem_coe, Finset.mem_union,
      Finset.mem_biUnion]
    right
    exact ⟨i, Finset.mem_univ _, j, Finset.mem_univ _,
      Finset.mem_image.mpr ⟨n, Finset.mem_range.mpr (by omega), rfl⟩⟩
  · rw [Polynomial.coeff_eq_zero_of_natDegree_lt (by omega : (B i j).natDegree < n)]
    exact (matrixCoefficientSubring B U).zero_mem

/-- Every coefficient lies in the Noetherian ring generated by the finite
matrix data and the initial coefficient vector. No Noetherian assumption on
its ambient commutative ring is required. -/
theorem matrixCoefficientSubring_series_mem
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K)
    (b : ℕ) (hb : 2 ≤ b)
    (hEq : ∀ i, U i = ∑ j, (B i j : PowerSeries K) * dilate b (U j))
    (i : ι) (n : ℕ) :
    PowerSeries.coeff n (U i) ∈ matrixCoefficientSubring B U := by
  classical
  induction n using Nat.strong_induction_on generalizing i with
  | h n ih =>
    by_cases hn : n = 0
    · subst n
      exact matrixCoefficientSubring_initial_mem B U i
    rw [hEq i, map_sum]
    apply Subring.sum_mem
    intro j hj
    rw [PowerSeries.coeff_mul, Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk]
    apply Subring.sum_mem
    intro a ha
    simp only [Polynomial.coeff_coe]
    apply Subring.mul_mem
    · exact matrixCoefficientSubring_polynomial_mem B U i j a
    · rw [coeff_dilate]
      split_ifs
      · apply ih ((n - a) / b)
        exact lt_of_le_of_lt (Nat.div_le_div_right (Nat.sub_le n a))
          (Nat.div_lt_self (by omega) (by omega))
      · exact (matrixCoefficientSubring B U).zero_mem

 theorem polynomialMatrix_exists_noetherian_coefficient_subring
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K)
    (b : ℕ) (hb : 2 ≤ b)
    (hEq : ∀ i, U i = ∑ j, (B i j : PowerSeries K) * dilate b (U j)) :
    ∃ S : Subring K, IsNoetherianRing S ∧
      (∀ i j n, (B i j).coeff n ∈ S) ∧
      (∀ i n, PowerSeries.coeff n (U i) ∈ S) := by
  exact ⟨matrixCoefficientSubring B U, inferInstance,
    matrixCoefficientSubring_polynomial_mem B U,
    fun i n => matrixCoefficientSubring_series_mem B U b hb hEq i n⟩

/-- The defining polynomial matrix descended to its finite coefficient ring. -/
noncomputable def matrixDescendedPolynomial
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K) (i j : ι) :
    Polynomial (matrixCoefficientSubring B U) :=
  { toFinsupp := .ofCoeff {
      support := (B i j).support
      toFun := fun n => ⟨(B i j).coeff n,
        matrixCoefficientSubring_polynomial_mem B U i j n⟩
      mem_support_toFun := fun n => by
        rw [ne_eq, ← Subring.coe_eq_zero_iff, Polynomial.mem_support_iff] } }

@[simp] theorem matrixDescendedPolynomial_coeff
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K) (i j : ι) (n : ℕ) :
    ((matrixDescendedPolynomial B U i j).coeff n : K) = (B i j).coeff n := rfl

@[simp] theorem matrixDescendedPolynomial_natDegree
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K) (i j : ι) :
    (matrixDescendedPolynomial B U i j).natDegree = (B i j).natDegree := rfl

noncomputable def matrixDescendedSeries
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K)
    (b : ℕ) (hb : 2 ≤ b)
    (hEq : ∀ i, U i = ∑ j, (B i j : PowerSeries K) * dilate b (U j))
    (i : ι) : PowerSeries (matrixCoefficientSubring B U) :=
  PowerSeries.mk fun n => ⟨PowerSeries.coeff n (U i),
    matrixCoefficientSubring_series_mem B U b hb hEq i n⟩

@[simp] theorem matrixDescendedSeries_coeff
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K)
    (b : ℕ) (hb : 2 ≤ b)
    (hEq : ∀ i, U i = ∑ j, (B i j : PowerSeries K) * dilate b (U j))
    (i : ι) (n : ℕ) :
    (PowerSeries.coeff (R := matrixCoefficientSubring B U) n
      (matrixDescendedSeries B U b hb hEq i) : K) = PowerSeries.coeff n (U i) := by
  simp [matrixDescendedSeries]

/-- The coefficient descent preserves the entire polynomial Mahler equation. -/
theorem matrixDescendedSeries_equation
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K)
    (b : ℕ) (hb : 2 ≤ b)
    (hEq : ∀ i, U i = ∑ j, (B i j : PowerSeries K) * dilate b (U j))
    (i : ι) :
    matrixDescendedSeries B U b hb hEq i = ∑ j,
      (matrixDescendedPolynomial B U i j : PowerSeries (matrixCoefficientSubring B U)) *
        dilate b (matrixDescendedSeries B U b hb hEq j) := by
  classical
  ext n
  simp only [matrixDescendedSeries_coeff, map_sum, PowerSeries.coeff_mul,
    map_sum (matrixCoefficientSubring B U).subtype, Subring.coe_mul, Polynomial.coeff_coe]
  conv_lhs => rw [hEq i]
  simp only [map_sum, PowerSeries.coeff_mul, Polynomial.coeff_coe]
  push_cast
  apply Finset.sum_congr rfl
  intro j hj
  apply Finset.sum_congr rfl
  intro p hp
  simp only [matrixDescendedPolynomial_coeff, coeff_dilate]
  split_ifs <;> simp

 theorem matrixDescendedSeries_jointSupport
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K)
    (b : ℕ) (hb : 2 ≤ b)
    (hEq : ∀ i, U i = ∑ j, (B i j : PowerSeries K) * dilate b (U j)) :
    polynomialMatrixJointSupport (matrixDescendedSeries B U b hb hEq) =
      polynomialMatrixJointSupport U := by
  funext n
  apply propext
  simp only [polynomialMatrixJointSupport]
  apply exists_congr
  intro i
  simp only [ne_eq]
  rw [← Subring.coe_eq_zero_iff]
  simp

@[simp] theorem matrixDescendedPolynomial_map
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K) (i j : ι) :
    (matrixDescendedPolynomial B U i j).map (matrixCoefficientSubring B U).subtype =
      B i j := by
  ext n
  simp

@[simp] theorem matrixDescendedSeries_map
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K)
    (b : ℕ) (hb : 2 ≤ b)
    (hEq : ∀ i, U i = ∑ j, (B i j : PowerSeries K) * dilate b (U j)) (i : ι) :
    PowerSeries.map (matrixCoefficientSubring B U).subtype
      (matrixDescendedSeries B U b hb hEq i) = U i := by
  ext n
  simp

/-- Every finite polynomial matrix Mahler system over any commutative ring
is the injective coefficient extension of a system over a Noetherian subring. -/
theorem polynomialMatrix_exists_noetherian_descent
    (B : ι → ι → Polynomial K) (U : ι → PowerSeries K)
    (b : ℕ) (hb : 2 ≤ b)
    (hEq : ∀ i, U i = ∑ j, (B i j : PowerSeries K) * dilate b (U j)) :
    ∃ S : Subring K, IsNoetherianRing S ∧
      ∃ (B' : ι → ι → Polynomial S) (U' : ι → PowerSeries S),
        (∀ i j, (B' i j).map S.subtype = B i j) ∧
        (∀ i, PowerSeries.map S.subtype (U' i) = U i) ∧
        (∀ i j, (B' i j).natDegree = (B i j).natDegree) ∧
        (∀ i, U' i = ∑ j, (B' i j : PowerSeries S) * dilate b (U' j)) := by
  exact ⟨matrixCoefficientSubring B U, inferInstance,
    matrixDescendedPolynomial B U, matrixDescendedSeries B U b hb hEq,
    matrixDescendedPolynomial_map B U, matrixDescendedSeries_map B U b hb hEq,
    matrixDescendedPolynomial_natDegree B U,
    matrixDescendedSeries_equation B U b hb hEq⟩

end IndependentZeroBlocks
