import SierpinskiFormal.FiniteLengthCompression
import SierpinskiFormal.ModuleReturnGroup
import SierpinskiFormal.RealWordGenerating
import SierpinskiFormal.CountableGroupCanonicalMean
import SierpinskiFormal.CesaroAbelTransfer
import SierpinskiFormal.WeightedWordEnumeration
import SierpinskiFormal.CommonContextLogDensity

/-!
# Rational central return means over Noetherian modules

A reset endomorphism factors through a return module.  If every compressed
return is supplied by a linear automorphism, marker gaps define a reversible
free-group action.  The exact physical-length renewal clock then identifies
the central word Abel mean with the return-group Abel mean.  Stability on the
ambient and return modules yields a rational Cesaro limit, independent of the
strictly positive IID letter law.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
noncomputable section

open Filter Set Topology
open scoped BigOperators Topology

namespace IndependentZeroBlocks

variable {R C X B : Type*} [CommRing R]
variable [AddCommGroup X] [Module R X] [AddCommGroup B] [Module R B]
variable [IsNoetherian R X] [IsNoetherian R (Module.Dual R X)]
variable [IsNoetherian R B] [IsNoetherian R (Module.Dual R B)]
variable [Fintype C] [Nonempty C] [DecidableEq C]
variable [TopologicalSpace C] [DiscreteTopology C]

/-- A fixed Abel parameter sequence approaching one from below. -/
def moduleCanonicalAbelParameter (n : ℕ) : ℝ :=
  1 - (((n + 2 : ℕ) : ℝ))⁻¹

theorem moduleCanonicalAbelParameter_nonneg (n : ℕ) :
    0 ≤ moduleCanonicalAbelParameter n := by
  unfold moduleCanonicalAbelParameter
  have htwo : (2 : ℝ) ≤ (n + 2 : ℕ) := by
    exact_mod_cast Nat.le_add_left 2 n
  have hinv : (((n + 2 : ℕ) : ℝ))⁻¹ ≤ 1 := by
    rw [inv_le_one₀ (by positivity : (0 : ℝ) < (n + 2 : ℕ))]
    exact le_trans (by norm_num : (1 : ℝ) ≤ 2) htwo
  linarith

theorem moduleCanonicalAbelParameter_lt_one (n : ℕ) :
    moduleCanonicalAbelParameter n < 1 := by
  unfold moduleCanonicalAbelParameter
  have : (0 : ℝ) < (((n + 2 : ℕ) : ℝ))⁻¹ := by positivity
  linarith

theorem tendsto_moduleCanonicalAbelParameter :
    Tendsto moduleCanonicalAbelParameter atTop (nhds 1) := by
  have htop : Tendsto (fun n : ℕ ↦ ((n + 2 : ℕ) : ℝ)) atTop atTop := by
    have hn : Tendsto (fun n : ℕ ↦ (n : ℝ)) atTop atTop :=
      tendsto_natCast_atTop_atTop
    have htwo : Tendsto (fun _ : ℕ ↦ (2 : ℝ)) atTop (nhds 2) :=
      tendsto_const_nhds
    simpa only [Nat.cast_add, Nat.cast_ofNat] using hn.atTop_add htwo
  have hinv : Tendsto (fun n : ℕ ↦ (((n + 2 : ℕ) : ℝ))⁻¹)
      atTop (nhds 0) := htop.inv_tendsto_atTop
  have hone : Tendsto (fun _ : ℕ ↦ (1 : ℝ)) atTop (nhds 1) :=
    tendsto_const_nhds
  have hsub : Tendsto
      (fun n : ℕ ↦ 1 - (((n + 2 : ℕ) : ℝ))⁻¹) atTop (nhds 1) := by
    simpa only [sub_zero] using hone.sub hinv
  change Tendsto (fun n : ℕ ↦ 1 - (((n + 2 : ℕ) : ℝ))⁻¹)
    atTop (nhds 1)
  exact hsub

/-- Boolean scalar observation of an ambient word compressed through the
return factorization. -/
def moduleCentralReturnPredicate
    (T : C → Module.End R X) (U : B →ₗ[R] X) (V : X →ₗ[R] B)
    (left : Module.Dual R B) (seed : B) (w : List C) : Bool :=
  nonzeroBool (left (compressedReturn T U V w seed))

/-- Exact-length IID expectation of the module central return predicate. -/
def moduleCentralReturnExactAverage
    (T : C → Module.End R X) (U : B →ₗ[R] X) (V : X →ₗ[R] B)
    (left : Module.Dual R B) (seed : B) (p : C → ℝ) (n : ℕ) : ℝ :=
  weightedWordExtensionAverage p
    (booleanWordIndicator (moduleCentralReturnPredicate T U V left seed)) n []

/-- Exact-support free-group predicate generated by the reversible compressed
returns of actual marker gaps. -/
def moduleCentralReturnGroupPredicate
    (K : List C → (B ≃ₗ[R] B)) (e : C)
    (left : Module.Dual R B) (seed : B) : FreeGroup (GapWords e) → Bool :=
  moduleReturnGroupPredicate (fun g : GapWords e ↦ K g.1) left seed

/-- Canonical marker gaps, carrying their marker-free proofs. -/
def moduleTypedMarkerGaps (e : C) (w : List C) : List (GapWords e) :=
  ((markerGapListsEquivNonemptyGapWords e) (markerGapEquiv e w)).1

/-- Send a marker-free word to its exact-support generator. -/
def moduleGapFreeGroupLetter (e : C) (y : List C) :
    FreeGroup (GapWords e) :=
  if hy : e ∉ y then FreeGroup.of ⟨y, hy⟩ else 1

@[simp] theorem moduleGapFreeGroupLetter_gap (e : C) (g : GapWords e) :
    moduleGapFreeGroupLetter e g.1 = FreeGroup.of g := by
  simp [moduleGapFreeGroupLetter, g.2]

theorem moduleTypedMarkerGaps_map_val (e : C) (w : List C) :
    (moduleTypedMarkerGaps e w).map Subtype.val = markerGaps e w := by
  simp [moduleTypedMarkerGaps, markerGapListsEquivNonemptyGapWords,
    markerGapEquiv]

theorem positiveFreeGroupWord_moduleTypedMarkerGaps (e : C) (w : List C) :
    positiveFreeGroupWord (moduleTypedMarkerGaps e w) =
      ((markerGaps e w).map (moduleGapFreeGroupLetter e)).prod := by
  unfold positiveFreeGroupWord
  rw [← moduleTypedMarkerGaps_map_val e w, List.map_map]
  apply congrArg List.prod
  apply List.map_congr_left
  intro g hg
  simp

/-- A positive list of actual gaps evaluates the compressed return of the
word formed by inserting the reset marker between consecutive gaps. -/
theorem moduleCentralReturnGroupPredicate_positiveGapWord
    (T : C → Module.End R X) (e : C)
    (U : B →ₗ[R] X) (V : X →ₗ[R] B)
    (hfac : endoWord T [e] = U.comp V)
    (K : List C → (B ≃ₗ[R] B))
    (hK : ∀ y, (K y).toLinearMap = compressedReturn T U V y)
    (left : Module.Dual R B) (seed : B)
    (g : GapWords e) (gs : List (GapWords e)) :
    moduleCentralReturnGroupPredicate K e left seed
        (positiveFreeGroupWord (g :: gs)) =
      moduleCentralReturnPredicate T U V left seed
        ([e].intercalate ((g :: gs).map Subtype.val)) := by
  unfold moduleCentralReturnGroupPredicate moduleCentralReturnPredicate
    moduleReturnGroupPredicate
  rw [moduleReturnFreeGroupAction_positiveWord]
  congr 2
  change ((g :: gs).map (fun d ↦ (K d.1).toLinearMap)).prod seed = _
  have hmaps : (g :: gs).map (fun d ↦ (K d.1).toLinearMap) =
      ((g :: gs).map Subtype.val).map (compressedReturn T U V) := by
    rw [List.map_map]
    apply List.map_congr_left
    intro d hd
    exact hK d.1
  rw [hmaps]
  have hprod := compressedReturn_prod_intercalate T [e] U V hfac g.1
    (gs.map Subtype.val)
  simpa using LinearMap.congr_fun hprod seed

/-- The canonical positive free-group word attached to all marker gaps of a
word evaluates to its original compressed central predicate. -/
theorem moduleCentralReturnGroupPredicate_typedMarkerGaps
    (T : C → Module.End R X) (e : C)
    (U : B →ₗ[R] X) (V : X →ₗ[R] B)
    (hfac : endoWord T [e] = U.comp V)
    (K : List C → (B ≃ₗ[R] B))
    (hK : ∀ y, (K y).toLinearMap = compressedReturn T U V y)
    (left : Module.Dual R B) (seed : B) (w : List C) :
    moduleCentralReturnGroupPredicate K e left seed
        (positiveFreeGroupWord (moduleTypedMarkerGaps e w)) =
      moduleCentralReturnPredicate T U V left seed w := by
  have hne : moduleTypedMarkerGaps e w ≠ [] := by
    intro hnil
    have hmap := congrArg (List.map Subtype.val) hnil
    rw [moduleTypedMarkerGaps_map_val] at hmap
    exact markerGaps_ne_nil e w (by simpa using hmap)
  cases hgs : moduleTypedMarkerGaps e w with
  | nil => exact (hne hgs).elim
  | cons g gs =>
      rw [moduleCentralReturnGroupPredicate_positiveGapWord
        T e U V hfac K hK left seed g gs]
      have hmap := congrArg (List.map Subtype.val) hgs
      rw [moduleTypedMarkerGaps_map_val] at hmap
      simpa [hmap] using congrArg
        (moduleCentralReturnPredicate T U V left seed)
        (intercalate_markerGaps e w)

/-- The physical central module observation is stable by the Noetherian
evaluation theorem on the ambient module. -/
theorem moduleCentralReturnPredicate_hasBooleanDoubleLimitProperty
    (T : C → Module.End R X) (U : B →ₗ[R] X) (V : X →ₗ[R] B)
    (left : Module.Dual R B) (seed : B) :
    HasBooleanDoubleLimitProperty (fun w z : List C ↦
      moduleCentralReturnPredicate T U V left seed (z ++ w)) := by
  have h := noetherian_linearWord_rightKernel_hasBooleanDoubleLimitProperty
    T (left.comp V) (U seed)
  simpa only [moduleCentralReturnPredicate, compressedReturn,
    LinearMap.comp_apply, endoWord, linearWord] using h

/-- Physical word-length central averages have a Cesaro limit for every
finite nonnegative normalized IID law. -/
theorem exists_tendsto_moduleCentralReturnCesaro
    (T : C → Module.End R X) (U : B →ₗ[R] X) (V : X →ₗ[R] B)
    (left : Module.Dual R B) (seed : B)
    (p : C → ℝ) (hp : ∀ c, 0 ≤ p c) (hp1 : ∑ c, p c = 1) :
    ∃ L : ℝ, Tendsto
      (realCesaroMean
        (moduleCentralReturnExactAverage T U V left seed p))
      atTop (nhds L) := by
  obtain ⟨L, hL⟩ := exists_tendsto_boolean_weighted_iid_word_cesaro
    p hp hp1 (moduleCentralReturnPredicate T U V left seed)
    (moduleCentralReturnPredicate_hasBooleanDoubleLimitProperty
      T U V left seed)
  refine ⟨L, ?_⟩
  have heq : realCesaroMean
      (moduleCentralReturnExactAverage T U V left seed p) =
      weightedIidWordCesaro p
        (booleanWordIndicator
          (moduleCentralReturnPredicate T U V left seed)) := by
    funext N
    unfold realCesaroMean weightedIidWordCesaro
      moduleCentralReturnExactAverage
    rw [div_eq_mul_inv]
    ring
  rw [heq]
  exact hL

/-- Every exact-length central average lies in `[0,1]`. -/
theorem moduleCentralReturnExactAverage_mem_Icc
    (T : C → Module.End R X) (U : B →ₗ[R] X) (V : X →ₗ[R] B)
    (left : Module.Dual R B) (seed : B)
    (p : C → ℝ) (hp : ∀ c, 0 ≤ p c) (hp1 : ∑ c, p c = 1)
    (n : ℕ) :
    moduleCentralReturnExactAverage T U V left seed p n ∈
      Set.Icc (0 : ℝ) 1 := by
  rw [moduleCentralReturnExactAverage,
    weightedWordExtensionAverage_eq_tuple_sum]
  constructor
  · exact Finset.sum_nonneg fun x hx ↦ mul_nonneg
      (wordWeight_nonneg p hp (List.ofFn x)) (by
        simp only [booleanWordIndicator_apply]
        cases hq : moduleCentralReturnPredicate T U V left seed
          (List.ofFn x) <;> simp [boolIndicator, hq])
  · calc
      (∑ x : Fin n → C, wordWeight p (List.ofFn x) *
          booleanWordIndicator
            (moduleCentralReturnPredicate T U V left seed)
            (List.ofFn x)) ≤
          ∑ x : Fin n → C, wordWeight p (List.ofFn x) := by
        apply Finset.sum_le_sum
        intro x hx
        have hw := wordWeight_nonneg p hp (List.ofFn x)
        apply mul_le_of_le_one_right hw
        cases hq : moduleCentralReturnPredicate T U V left seed
          (List.ofFn x) <;> simp [boolIndicator, hq]
      _ = 1 := sum_tuple_wordWeight_eq_one p hp1 n

/-- Any Cesaro limit of the central exact-length averages is a probability
value. -/
theorem moduleCentralReturnCesaroLimit_mem_Icc
    (T : C → Module.End R X) (U : B →ₗ[R] X) (V : X →ₗ[R] B)
    (left : Module.Dual R B) (seed : B)
    (p : C → ℝ) (hp : ∀ c, 0 ≤ p c) (hp1 : ∑ c, p c = 1)
    (L : ℝ)
    (hL : Tendsto (realCesaroMean
      (moduleCentralReturnExactAverage T U V left seed p))
      atTop (nhds L)) : L ∈ Set.Icc (0 : ℝ) 1 := by
  constructor
  · apply ge_of_tendsto hL
    exact Eventually.of_forall fun N ↦ realCesaroMean_nonneg
      (fun n ↦ (moduleCentralReturnExactAverage_mem_Icc
        T U V left seed p hp hp1 n).1) N
  · apply le_of_tendsto hL
    filter_upwards [eventually_gt_atTop 0] with N hN
    exact realCesaroMean_le_one
      (fun n ↦ (moduleCentralReturnExactAverage_mem_Icc
        T U V left seed p hp hp1 n).2) hN

def moduleCentralReturnGapLaw (p : C → ℝ) (e : C) (s : ℝ) :
    GapWords e → ℝ :=
  tiltedGapLaw (realNonMarkerMass p e) s p e

def moduleCentralReturnDiscount (p : C → ℝ) (e : C) (s : ℝ) : ℝ :=
  renewalMarkerDiscount (realNonMarkerMass p e) s

/-- Exact normalized physical-length Abel identity with the `k+1` marker-gap
convention. -/
theorem moduleCentralReturnNormalizedAbelMean_eq_geometricGapMoments
    (T : C → Module.End R X) (e : C)
    (U : B →ₗ[R] X) (V : X →ₗ[R] B)
    (hfac : endoWord T [e] = U.comp V)
    (K : List C → (B ≃ₗ[R] B))
    (hK : ∀ y, (K y).toLinearMap = compressedReturn T U V y)
    (left : Module.Dual R B) (seed : B)
    (p : C → ℝ) (hp : ∀ c, 0 < p c) (hp1 : ∑ c, p c = 1)
    (s : ℝ) (hs0 : 0 ≤ s) (hs1 : s < 1) :
    realNormalizedAbelMean
        (moduleCentralReturnExactAverage T U V left seed p) s =
      (1 - moduleCentralReturnDiscount p e s) *
        ∑' k : ℕ, moduleCentralReturnDiscount p e s ^ k *
          countableGroupTupleMoment
            (moduleCentralReturnGroupPredicate K e left seed)
            (FreeGroup.of : GapWords e → FreeGroup (GapWords e))
            (moduleCentralReturnGapLaw p e s) 1 1 (k + 1) := by
  let qG : FreeGroup (GapWords e) → Bool :=
    moduleCentralReturnGroupPredicate K e left seed
  let code : List C → FreeGroup (GapWords e) := fun w ↦
    positiveFreeGroupWord (moduleTypedMarkerGaps e w)
  have hcode : ∀ w, code w =
      ((markerGaps e w).map (moduleGapFreeGroupLetter e)).prod := by
    intro w
    exact positiveFreeGroupWord_moduleTypedMarkerGaps e w
  have hpredicate : (fun w ↦ qG (code w)) =
      moduleCentralReturnPredicate T U V left seed := by
    funext w
    exact moduleCentralReturnGroupPredicate_typedMarkerGaps
      T e U V hfac K hK left seed w
  have hp0 : ∀ c, 0 ≤ p c := fun c ↦ (hp c).le
  have hrlt : realNonMarkerMass p e < 1 := by
    rw [realNonMarkerMass_eq_one_sub p e hp1]
    linarith [hp e]
  letI : TopologicalSpace (FreeGroup (GapWords e)) := ⊥
  letI : DiscreteTopology (FreeGroup (GapWords e)) := ⟨rfl⟩
  have hrenewal := realNormalizedAbelMean_eq_geometricGapMoments
    e (realNonMarkerMass p e) s p hp0 hp1 rfl hrlt hs0 hs1
      (moduleGapFreeGroupLetter e) code qG hcode
  rw [hpredicate] at hrenewal
  unfold moduleCentralReturnExactAverage
  simpa only [
    moduleCentralReturnDiscount, moduleCentralReturnGapLaw, qG,
    moduleGapFreeGroupLetter_gap] using hrenewal

/-- For fixed module returns and boundary data, one rational number is the
physical word-length Cesaro limit for every strictly positive normalized IID
letter law. -/
theorem exists_rational_forall_tendsto_moduleCentralReturnCesaro
    (T : C → Module.End R X) (e : C)
    (U : B →ₗ[R] X) (V : X →ₗ[R] B)
    (hfac : endoWord T [e] = U.comp V)
    (K : List C → (B ≃ₗ[R] B))
    (hK : ∀ y, (K y).toLinearMap = compressedReturn T U V y)
    (left : Module.Dual R B) (seed : B) :
    ∃ q : ℚ, ∀ (p : C → ℝ), (∀ c, 0 < p c) → (∑ c, p c = 1) →
      Tendsto (realCesaroMean
        (moduleCentralReturnExactAverage T U V left seed p))
        atTop (nhds (q : ℝ)) := by
  let qG : FreeGroup (GapWords e) → Bool :=
    moduleCentralReturnGroupPredicate K e left seed
  let step : GapWords e → FreeGroup (GapWords e) := FreeGroup.of
  let pRef : C → ℝ := uniformAlphabetWeight
  let rRef : ℝ := realNonMarkerMass pRef e
  let referenceWeight : GapWords e → ℝ :=
    moduleCentralReturnGapLaw pRef e 1
  letI : Countable (GapWords e) := Subtype.val_injective.countable
  letI : TopologicalSpace (FreeGroup (GapWords e)) := ⊥
  letI : DiscreteTopology (FreeGroup (GapWords e)) := ⟨rfl⟩
  letI : Countable (FreeGroup (GapWords e)) :=
    (moduleReturnFreeGroup_countable_and_generated (GapWords e)).1
  have hDLP : HasBooleanDoubleLimitProperty (booleanGroupRightRow qG) := by
    exact moduleReturnGroupPredicate_hasBooleanDoubleLimitProperty
      (fun g : GapWords e ↦ K g.1) left seed
  have hpRefPos : ∀ c, 0 < pRef c := by
    intro c
    exact uniformAlphabetWeight_pos c
  have hpRef0 : ∀ c, 0 ≤ pRef c := fun c ↦ (hpRefPos c).le
  have hpRef1 : ∑ c, pRef c = 1 := sum_uniformAlphabetWeight
  have hrRefLt : rRef < 1 := by
    dsimp [rRef]
    rw [realNonMarkerMass_eq_one_sub pRef e hpRef1]
    linarith [hpRefPos e]
  have href_pos : ∀ d, 0 < referenceWeight d := by
    intro d
    exact tiltedGapLaw_pos_at_one rRef pRef e hpRefPos hrRefLt d
  have href_sum : HasSum referenceWeight 1 := by
    exact hasSum_tiltedGapLaw_one rRef 1 pRef e hpRef0 rfl hrRefLt
      zero_le_one le_rfl
  have hgenerate : Subgroup.closure (Set.range step) = ⊤ := by
    exact (moduleReturnFreeGroup_countable_and_generated (GapWords e)).2
  obtain ⟨q, hq⟩ :=
    exists_canonical_rational_tendsto_all_countableGroupTupleAbel_succ
      qG hDLP step referenceWeight href_pos href_sum hgenerate
  refine ⟨q, ?_⟩
  intro p hp hp1
  let r₀ := realNonMarkerMass p e
  let weight : ℕ → GapWords e → ℝ := fun n ↦
    moduleCentralReturnGapLaw p e (moduleCanonicalAbelParameter n)
  let weightLim : GapWords e → ℝ := moduleCentralReturnGapLaw p e 1
  let discount : ℕ → ℝ := fun n ↦
    moduleCentralReturnDiscount p e (moduleCanonicalAbelParameter n)
  have hp0 : ∀ c, 0 ≤ p c := fun c ↦ (hp c).le
  have hr₀_nonneg : 0 ≤ r₀ := by
    dsimp [r₀, realNonMarkerMass]
    exact Finset.sum_nonneg fun c hc ↦ by
      by_cases hce : c = e <;> simp [hce, hp0 c]
  have hr₀_lt : r₀ < 1 := by
    dsimp [r₀]
    rw [realNonMarkerMass_eq_one_sub p e hp1]
    linarith [hp e]
  have hweight : ∀ n g, 0 ≤ weight n g := by
    intro n g
    exact tiltedGapLaw_nonneg r₀ (moduleCanonicalAbelParameter n) p e hp0
      hr₀_nonneg hr₀_lt.le (moduleCanonicalAbelParameter_nonneg n)
      (moduleCanonicalAbelParameter_lt_one n).le g
  have hweight_sum : ∀ n, HasSum (weight n) 1 := by
    intro n
    exact hasSum_tiltedGapLaw_one r₀ (moduleCanonicalAbelParameter n) p e
      hp0 rfl hr₀_lt (moduleCanonicalAbelParameter_nonneg n)
      (moduleCanonicalAbelParameter_lt_one n).le
  have hweightLim : ∀ g, 0 < weightLim g := by
    intro g
    exact tiltedGapLaw_pos_at_one r₀ p e hp hr₀_lt g
  have hweightLim_sum : HasSum weightLim 1 :=
    hasSum_tiltedGapLaw_one r₀ 1 p e hp0 rfl hr₀_lt zero_le_one le_rfl
  have hdiff : ∀ n, Summable fun g ↦ |weight n g - weightLim g| := by
    intro n
    exact ((hweight_sum n).summable.sub hweightLim_sum.summable).abs
  have hsWithin : Tendsto moduleCanonicalAbelParameter atTop
      (nhdsWithin (1 : ℝ) (Set.Icc 0 1)) := by
    apply tendsto_nhdsWithin_iff.2
    exact ⟨tendsto_moduleCanonicalAbelParameter,
      Eventually.of_forall fun n ↦
        ⟨moduleCanonicalAbelParameter_nonneg n,
          (moduleCanonicalAbelParameter_lt_one n).le⟩⟩
  have hl1 : Tendsto
      (fun n ↦ ∑' g, |weight n g - weightLim g|) atTop (nhds 0) := by
    exact (tendsto_tiltedGapLaw_discreteL1_of_nonMarkerMass_lt_one
      p e hp0 hr₀_lt).comp hsWithin
  have hdiscount : ∀ n, 0 ≤ discount n := by
    intro n
    exact renewalMarkerDiscount_nonneg r₀ (moduleCanonicalAbelParameter n)
      hr₀_nonneg hr₀_lt.le (moduleCanonicalAbelParameter_nonneg n)
      (moduleCanonicalAbelParameter_lt_one n).le
  have hdiscount_lt : ∀ n, discount n < 1 := by
    intro n
    exact renewalMarkerDiscount_lt_one r₀ (moduleCanonicalAbelParameter n)
      hr₀_nonneg hr₀_lt (moduleCanonicalAbelParameter_nonneg n)
      (moduleCanonicalAbelParameter_lt_one n)
  have hdiscount_one : Tendsto discount atTop (nhds 1) :=
    tendsto_renewalMarkerDiscount_one r₀ moduleCanonicalAbelParameter
      hr₀_lt tendsto_moduleCanonicalAbelParameter
  have htuple := hq weight weightLim hweight hweight_sum hweightLim
    hweightLim_sum hdiff hl1 discount hdiscount hdiscount_lt
      hdiscount_one (1 : FreeGroup (GapWords e))
  have hqPhysical : Tendsto (fun n ↦
      realNormalizedAbelMean
        (moduleCentralReturnExactAverage T U V left seed p)
        (moduleCanonicalAbelParameter n)) atTop (nhds (q : ℝ)) := by
    apply htuple.congr'
    exact Eventually.of_forall fun n ↦ by
      simpa [qG, step, weight, discount, moduleCentralReturnGapLaw,
        moduleCentralReturnDiscount] using
        (moduleCentralReturnNormalizedAbelMean_eq_geometricGapMoments
          T e U V hfac K hK left seed p hp hp1
            (moduleCanonicalAbelParameter n)
            (moduleCanonicalAbelParameter_nonneg n)
            (moduleCanonicalAbelParameter_lt_one n)).symm
  obtain ⟨L, hL⟩ := exists_tendsto_moduleCentralReturnCesaro
    T U V left seed p hp0 hp1
  have hbound : ∀ n,
      |moduleCentralReturnExactAverage T U V left seed p n| ≤ 1 := by
    intro n
    have hn := moduleCentralReturnExactAverage_mem_Icc
      T U V left seed p hp0 hp1 n
    rw [abs_of_nonneg hn.1]
    exact hn.2
  have hAbel := tendsto_realNormalizedAbelMean_of_tendsto_realCesaroMean
    (moduleCentralReturnExactAverage T U V left seed p) 1 L hbound hL
  have hsBelow : Tendsto moduleCanonicalAbelParameter atTop
      (nhdsWithin (1 : ℝ) (Set.Iio 1)) := by
    apply tendsto_nhdsWithin_iff.2
    exact ⟨tendsto_moduleCanonicalAbelParameter,
      Eventually.of_forall moduleCanonicalAbelParameter_lt_one⟩
  have hLPhysical := hAbel.comp hsBelow
  have hLq : L = (q : ℝ) := tendsto_nhds_unique hLPhysical hqPhysical
  exact hLq ▸ hL

/-- Per-law rationality as a direct corollary of the canonical all-law mean. -/
theorem exists_rational_tendsto_moduleCentralReturnCesaro
    (T : C → Module.End R X) (e : C)
    (U : B →ₗ[R] X) (V : X →ₗ[R] B)
    (hfac : endoWord T [e] = U.comp V)
    (K : List C → (B ≃ₗ[R] B))
    (hK : ∀ y, (K y).toLinearMap = compressedReturn T U V y)
    (left : Module.Dual R B) (seed : B)
    (p : C → ℝ) (hp : ∀ c, 0 < p c) (hp1 : ∑ c, p c = 1) :
    ∃ q : ℚ, Tendsto (realCesaroMean
      (moduleCentralReturnExactAverage T U V left seed p))
      atTop (nhds (q : ℝ)) := by
  obtain ⟨q, hq⟩ := exists_rational_forall_tendsto_moduleCentralReturnCesaro
    T e U V hfac K hK left seed
  exact ⟨q, hq p hp hp1⟩

/-- The canonical law-independent rational mean can be chosen together with
its intrinsic probability bound. -/
theorem exists_rational_mem_Icc_forall_tendsto_moduleCentralReturnCesaro
    (T : C → Module.End R X) (e : C)
    (U : B →ₗ[R] X) (V : X →ₗ[R] B)
    (hfac : endoWord T [e] = U.comp V)
    (K : List C → (B ≃ₗ[R] B))
    (hK : ∀ y, (K y).toLinearMap = compressedReturn T U V y)
    (left : Module.Dual R B) (seed : B) :
    ∃ q : ℚ, (q : ℝ) ∈ Set.Icc (0 : ℝ) 1 ∧
      ∀ (p : C → ℝ), (∀ c, 0 < p c) → (∑ c, p c = 1) →
        Tendsto (realCesaroMean
          (moduleCentralReturnExactAverage T U V left seed p))
          atTop (nhds (q : ℝ)) := by
  obtain ⟨q, hq⟩ := exists_rational_forall_tendsto_moduleCentralReturnCesaro
    T e U V hfac K hK left seed
  let pRef : C → ℝ := uniformAlphabetWeight
  have hpRefPos : ∀ c, 0 < pRef c := fun c ↦ uniformAlphabetWeight_pos c
  have hpRef1 : ∑ c, pRef c = 1 := sum_uniformAlphabetWeight
  have hbound := moduleCentralReturnCesaroLimit_mem_Icc
    T U V left seed pRef (fun c ↦ (hpRefPos c).le) hpRef1 (q : ℝ)
      (hq pRef hpRefPos hpRef1)
  exact ⟨q, hbound, hq⟩

end IndependentZeroBlocks
