import SierpinskiFormal.NoetherianObservationDLP
import SierpinskiFormal.ReversibleSequenceSections
import Mathlib.RingTheory.HopkinsLevitzki

set_option autoImplicit false

/-!
# Abstract reversible return groups over modules

This module separates the reversible group argument from matrix coordinates.
A family of linear equivalences on a module gives a free-group action and a
stable scalar observation.  A second interface treats arbitrary
endomorphism-valued word maps satisfying the chronological append law; this
is the direct integration point for finite-length return compression.
-/

noncomputable section

open Filter Set
open scoped Topology BigOperators

namespace IndependentZeroBlocks

section EndomorphismWords

variable {R V A : Type*} [CommRing R] [AddCommGroup V] [Module R V]
  [IsNoetherian R V] [IsNoetherian R (Module.Dual R V)]

/-- A chronological endomorphism-valued word observation is stable as soon
as concatenation is represented by multiplication.  No finiteness
assumption on the word alphabet is needed. -/
theorem noetherian_endoWord_rightKernel_hasBooleanDoubleLimitProperty
    (wordEnd : List A → Module.End R V)
    (wordEnd_append : ∀ z w, wordEnd (z ++ w) = wordEnd z * wordEnd w)
    (left : Module.Dual R V) (seed : V) :
    HasBooleanDoubleLimitProperty (fun w z : List A ↦
      nonzeroBool (left (wordEnd (z ++ w) seed))) := by
  have h := noetherianEvaluation_hasBooleanDoubleLimitProperty
    (fun w ↦ wordEnd w seed) (fun z ↦ left.comp (wordEnd z))
  simpa only [wordEnd_append, Module.End.mul_apply, LinearMap.comp_apply] using h

/-- Specialization of the generic endomorphism-word kernel to `linearWord`. -/
theorem noetherian_linearWord_rightKernel_hasBooleanDoubleLimitProperty
    (T : A → Module.End R V) (left : Module.Dual R V) (seed : V) :
    HasBooleanDoubleLimitProperty (fun w z : List A ↦
      nonzeroBool (left (linearWord T (z ++ w) seed))) := by
  exact noetherian_endoWord_rightKernel_hasBooleanDoubleLimitProperty
    (linearWord T) (linearWord_append T) left seed

variable [TopologicalSpace A] [DiscreteTopology A] [Fintype A] [Nonempty A]

/-- Stable endomorphism-word coefficients have a Cesaro limit under every
finite nonnegative normalized letter law. -/
theorem exists_tendsto_noetherian_endoWord_weighted_cesaro
    (wordEnd : List A → Module.End R V)
    (wordEnd_append : ∀ z w, wordEnd (z ++ w) = wordEnd z * wordEnd w)
    (left : Module.Dual R V) (seed : V)
    (p : A → ℝ) (hp : ∀ a, 0 ≤ p a) (hp1 : ∑ a, p a = 1) :
    ∃ L : ℝ, Tendsto
      (weightedIidWordCesaro p (booleanWordIndicator
        (fun w ↦ nonzeroBool (left (wordEnd w seed)))))
      atTop (nhds L) := by
  exact exists_tendsto_boolean_weighted_iid_word_cesaro p hp hp1 _
    (noetherian_endoWord_rightKernel_hasBooleanDoubleLimitProperty
      wordEnd wordEnd_append left seed)

/-- `linearWord` form of the generic endomorphism-word Cesaro theorem. -/
theorem exists_tendsto_noetherian_linearWord_weighted_cesaro
    (T : A → Module.End R V) (left : Module.Dual R V) (seed : V)
    (p : A → ℝ) (hp : ∀ a, 0 ≤ p a) (hp1 : ∑ a, p a = 1) :
    ∃ L : ℝ, Tendsto
      (weightedIidWordCesaro p (booleanWordIndicator
        (fun w ↦ nonzeroBool (left (linearWord T w seed)))))
      atTop (nhds L) := by
  exact exists_tendsto_noetherian_endoWord_weighted_cesaro
    (linearWord T) (linearWord_append T) left seed p hp hp1

end EndomorphismWords

section ReturnGroup

variable {R B D : Type*} [CommRing R] [AddCommGroup B] [Module R B]

/-- The free-group action generated by an abstract family of reversible
return endomorphisms. -/
def moduleReturnFreeGroupAction (K : D → (B ≃ₗ[R] B)) :
    FreeGroup D →* (B ≃ₗ[R] B) :=
  freeGroupLinearAction K

@[simp] theorem moduleReturnFreeGroupAction_of_apply
    (K : D → (B ≃ₗ[R] B)) (d : D) (b : B) :
    moduleReturnFreeGroupAction K (FreeGroup.of d) b = K d b := by
  rw [moduleReturnFreeGroupAction, freeGroupLinearAction_of]

/-- A positive free-group word acts by the chronological product of the
underlying return endomorphisms. -/
theorem moduleReturnFreeGroupAction_positiveWord_toLinearMap
    (K : D → (B ≃ₗ[R] B)) (ds : List D) :
    (moduleReturnFreeGroupAction K
      (positiveFreeGroupWord ds)).toLinearMap =
      (ds.map (fun d ↦ (K d).toLinearMap)).prod := by
  induction ds with
  | nil =>
      simp [moduleReturnFreeGroupAction, positiveFreeGroupWord]
      rfl
  | cons d ds ih =>
      simp only [positiveFreeGroupWord, List.map_cons, List.prod_cons, map_mul,
        LinearEquiv.coe_toLinearMap_mul]
      rw [moduleReturnFreeGroupAction, freeGroupLinearAction_of]
      change (K d).toLinearMap *
          (moduleReturnFreeGroupAction K
            (positiveFreeGroupWord ds)).toLinearMap = _
      rw [ih]

/-- Pointwise form of positive-word evaluation. -/
theorem moduleReturnFreeGroupAction_positiveWord
    (K : D → (B ≃ₗ[R] B)) (ds : List D) (b : B) :
    moduleReturnFreeGroupAction K (positiveFreeGroupWord ds) b =
      (ds.map (fun d ↦ (K d).toLinearMap)).prod b := by
  have h := LinearMap.congr_fun
    (moduleReturnFreeGroupAction_positiveWord_toLinearMap K ds) b
  exact h

/-- The reversible action, regarded as an endomorphism representation for
the Noetherian observation theorem. -/
def moduleReturnFreeGroupEndRepresentation (K : D → (B ≃ₗ[R] B)) :
    FreeGroup D →* Module.End R B where
  toFun g := (moduleReturnFreeGroupAction K g).toLinearMap
  map_one' := by
    apply LinearMap.ext
    intro b
    change moduleReturnFreeGroupAction K 1 b = b
    simp
  map_mul' g h := by
    apply LinearMap.ext
    intro b
    change moduleReturnFreeGroupAction K (g * h) b =
      moduleReturnFreeGroupAction K g (moduleReturnFreeGroupAction K h b)
    rw [map_mul, LinearEquiv.mul_apply]

/-- Boolean scalar observation of the abstract return-group action. -/
def moduleReturnGroupPredicate (K : D → (B ≃ₗ[R] B))
    (left : Module.Dual R B) (seed : B) (g : FreeGroup D) : Bool :=
  nonzeroBool (left (moduleReturnFreeGroupAction K g seed))

/-- On a positive word, the group predicate is the scalar observation of
the corresponding chronological endomorphism product. -/
theorem moduleReturnGroupPredicate_positiveWord
    (K : D → (B ≃ₗ[R] B)) (left : Module.Dual R B) (seed : B)
    (ds : List D) :
    moduleReturnGroupPredicate K left seed (positiveFreeGroupWord ds) =
      nonzeroBool
        (left ((ds.map (fun d ↦ (K d).toLinearMap)).prod seed)) := by
  rw [moduleReturnGroupPredicate, moduleReturnFreeGroupAction_positiveWord]

/-- Abstract return-group scalar observations are stable for an arbitrary
generator type `D`. -/
theorem moduleReturnGroupPredicate_hasBooleanDoubleLimitProperty
    [IsNoetherian R B] [IsNoetherian R (Module.Dual R B)]
    (K : D → (B ≃ₗ[R] B)) (left : Module.Dual R B) (seed : B) :
    HasBooleanDoubleLimitProperty
      (booleanGroupRightRow (moduleReturnGroupPredicate K left seed)) := by
  change HasBooleanDoubleLimitProperty (fun g h ↦
    nonzeroBool (left (moduleReturnFreeGroupAction K (h * g) seed)))
  have H := noetherian_groupObservation_rightRow_hasBooleanDoubleLimitProperty
    (moduleReturnFreeGroupEndRepresentation K) left seed
  have H' : HasBooleanDoubleLimitProperty (fun g h ↦
      nonzeroBool (left ((moduleReturnFreeGroupEndRepresentation K h)
        ((moduleReturnFreeGroupEndRepresentation K g) seed)))) := by
    simpa only [map_mul, Module.End.mul_apply] using H
  have hrep (g : FreeGroup D) (b : B) :
      moduleReturnFreeGroupEndRepresentation K g b =
        moduleReturnFreeGroupAction K g b := rfl
  simpa only [map_mul, LinearEquiv.mul_apply, hrep] using H'

/-- The canonical generators generate the entire abstract return free
group; countability of the support type gives countability of the group. -/
theorem moduleReturnFreeGroup_countable_and_generated
    (D : Type*) [Countable D] :
    Countable (FreeGroup D) ∧
      Subgroup.closure (Set.range (FreeGroup.of : D → FreeGroup D)) = ⊤ := by
  exact ⟨by infer_instance, freeGroup_closure_range_of_eq_top D⟩

/-- An injective encoding of the return alphabet into any countable type
supplies the countability needed by the group-law arguments. -/
theorem moduleReturnFreeGroup_countable_and_generated_of_injective
    {E : Type*} (encode : D → E) (hencode : Function.Injective encode)
    [Countable E] :
    Countable (FreeGroup D) ∧
      Subgroup.closure (Set.range (FreeGroup.of : D → FreeGroup D)) = ⊤ := by
  letI : Countable D := hencode.countable
  exact moduleReturnFreeGroup_countable_and_generated D

end ReturnGroup

section ArtinianBridge

variable {R B D : Type*} [CommRing R] [IsArtinianRing R]
  [AddCommGroup B] [Module R B] [Module.Finite R B]

/-- Over a commutative Artinian ring, a finite module and its algebraic
dual are both Noetherian. -/
theorem artinian_finite_module_and_dual_isNoetherian :
    IsNoetherian R B ∧ IsNoetherian R (Module.Dual R B) := by
  exact ⟨by infer_instance, by infer_instance⟩

/-- Artinian finite-module form of abstract return-group stability, with
the Noetherian hypotheses inferred automatically. -/
theorem artinian_finite_moduleReturnGroupPredicate_hasBooleanDoubleLimitProperty
    (K : D → (B ≃ₗ[R] B)) (left : Module.Dual R B) (seed : B) :
    HasBooleanDoubleLimitProperty
      (booleanGroupRightRow (moduleReturnGroupPredicate K left seed)) := by
  exact moduleReturnGroupPredicate_hasBooleanDoubleLimitProperty K left seed

end ArtinianBridge

end IndependentZeroBlocks
