import SierpinskiFormal.ObservableNoetherian
import SierpinskiFormal.CommRingObservationGeometry

set_option autoImplicit false

namespace IndependentZeroBlocks

open scoped BigOperators

section AbstractNoetherian

variable {R V : Type*} [CommRing R] [AddCommGroup V] [Module R V]

/-- A finite family of natural-number indices is bounded by the successor of
its supremum. -/
private theorem index_lt_sup_add_one {d : ℕ} (w : Fin d → ℕ) (i : Fin d) :
    w i < Finset.univ.sup w + 1 := by
  exact Nat.lt_succ_of_le (Finset.le_sup (Finset.mem_univ i))

/-- A Noetherian module admits no infinite upper-zero evaluation staircase:
earlier rows cannot all vanish on a later column while every diagonal
pairing remains nonzero. -/
theorem noetherian_no_upper_evaluation_staircase
    [IsNoetherian R V]
    (rows : ℕ → V) (cols : ℕ → Module.Dual R V)
    (hzero : ∀ i j : ℕ, i < j → cols j (rows i) = 0)
    (hdiag : ∀ i : ℕ, cols i (rows i) ≠ 0) : False := by
  have hfg : (Submodule.span R (Set.range rows)).FG :=
    isNoetherian_def.mp inferInstance _
  obtain ⟨d, w, hspan⟩ :=
    finite_original_generators_of_fg_span_range rows hfg
  let n := Finset.univ.sup w + 1
  have hrn : rows n ∈ Submodule.span R (Set.range fun i ↦ rows (w i)) := by
    rw [hspan]
    exact Submodule.subset_span ⟨n, rfl⟩
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun R).mp hrn
  have heval := congrArg (fun x : V ↦ cols n x) hc
  have hz : ∀ i : Fin d, cols n (rows (w i)) = 0 := by
    intro i
    exact hzero (w i) n (index_lt_sup_add_one w i)
  simp only [map_sum, map_smul, hz, smul_zero, Finset.sum_const_zero] at heval
  exact hdiag n heval.symm

/-- A module with Noetherian dual admits no infinite lower-zero evaluation
staircase: an earlier column cannot vanish on every later row while every
diagonal pairing remains nonzero. -/
theorem noetherianDual_no_lower_evaluation_staircase
    [IsNoetherian R (Module.Dual R V)]
    (rows : ℕ → V) (cols : ℕ → Module.Dual R V)
    (hzero : ∀ i j : ℕ, i < j → cols i (rows j) = 0)
    (hdiag : ∀ i : ℕ, cols i (rows i) ≠ 0) : False := by
  have hfg : (Submodule.span R (Set.range cols)).FG :=
    isNoetherian_def.mp inferInstance _
  obtain ⟨d, w, hspan⟩ :=
    finite_original_generators_of_fg_span_range cols hfg
  let n := Finset.univ.sup w + 1
  have hcn : cols n ∈ Submodule.span R (Set.range fun i ↦ cols (w i)) := by
    rw [hspan]
    exact Submodule.subset_span ⟨n, rfl⟩
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun R).mp hcn
  let ev : Module.Dual R (Module.Dual R V) :=
    LinearMap.applyₗ (R := R) (M := V) (M₂ := R) (rows n)
  have heval := congrArg (fun l : Module.Dual R V ↦ ev l) hc
  have hz : ∀ i : Fin d, cols (w i) (rows n) = 0 := by
    intro i
    exact hzero (w i) n (index_lt_sup_add_one w i)
  change (∑ i, c i • cols (w i)) (rows n) = cols n (rows n) at heval
  simp only [LinearMap.sum_apply, LinearMap.smul_apply, hz, smul_zero,
    Finset.sum_const_zero] at heval
  exact hdiag n heval.symm

end AbstractNoetherian

section FiniteFree

variable {R ι : Type*} [CommRing R] [IsNoetherianRing R] [Fintype ι]

/-- Finite free coordinate modules over Noetherian commutative rings have no
upper-zero evaluation staircase. -/
theorem finiteFree_no_upper_evaluation_staircase
    (rows : ℕ → ι → R) (cols : ℕ → Module.Dual R (ι → R))
    (hzero : ∀ i j : ℕ, i < j → cols j (rows i) = 0)
    (hdiag : ∀ i : ℕ, cols i (rows i) ≠ 0) : False := by
  exact noetherian_no_upper_evaluation_staircase rows cols hzero hdiag

/-- Finite free coordinate modules over Noetherian commutative rings have no
lower-zero evaluation staircase. -/
theorem finiteFree_no_lower_evaluation_staircase
    (rows : ℕ → ι → R) (cols : ℕ → Module.Dual R (ι → R))
    (hzero : ∀ i j : ℕ, i < j → cols i (rows j) = 0)
    (hdiag : ∀ i : ℕ, cols i (rows i) ≠ 0) : False := by
  exact noetherianDual_no_lower_evaluation_staircase rows cols hzero hdiag

end FiniteFree


section WordCoefficientDescent

variable {K ι : Type*} [CommRing K] [Fintype ι]

/-- The seed of a finite matrix-word representation, descended to the
Noetherian subring generated by the matrices, seed, and observation row. -/
noncomputable def linearWordDescendedSeed
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u a : ι → K) :
    ι → linearObservationCoefficientSubring M (fun _ : ℕ ↦ u) a :=
  fun i ↦ ⟨u i,
    linearObservationCoefficientSubring_seed_mem M (fun _ : ℕ ↦ u) a i⟩

@[simp] theorem linearWordDescendedSeed_coe
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u a : ι → K) (i : ι) :
    (linearWordDescendedSeed M u a i : K) = u i := rfl

/-- Descending all finite matrix data preserves every coordinate after every
finite word. -/
theorem linearWord_descended_state_coe
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u a : ι → K)
    (w : List (Fin b)) (i : ι) :
    ((linearWord
        (fun r ↦ Matrix.mulVecLin
          (linearObservationDescendedMatrix M (fun _ : ℕ ↦ u) a r)) w
        (linearWordDescendedSeed M u a) i :
          linearObservationCoefficientSubring M (fun _ : ℕ ↦ u) a) : K) =
      linearWord (fun r ↦ Matrix.mulVecLin (M r)) w u i := by
  classical
  induction w generalizing i with
  | nil => simp [linearWordDescendedSeed]
  | cons r w ih =>
      rw [linearWord_cons, linearWord_cons, Module.End.mul_apply,
        Module.End.mul_apply]
      change ((∑ j,
        linearObservationDescendedMatrix M (fun _ : ℕ ↦ u) a r i j *
          linearWord
            (fun r ↦ Matrix.mulVecLin
              (linearObservationDescendedMatrix M (fun _ : ℕ ↦ u) a r)) w
            (linearWordDescendedSeed M u a) j :
              linearObservationCoefficientSubring M (fun _ : ℕ ↦ u) a) : K) =
        ∑ j, M r i j *
          linearWord (fun r ↦ Matrix.mulVecLin (M r)) w u j
      push_cast
      apply Finset.sum_congr rfl
      intro j hj
      rw [linearObservationDescendedMatrix_coe, ih]

/-- Descending all finite matrix data preserves the scalar value of every
word. -/
theorem linearWord_descended_evaluation_coe
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u a : ι → K)
    (w : List (Fin b)) :
    ((coordinateRowDual
        (linearObservationDescendedRow M (fun _ : ℕ ↦ u) a)
        (linearWord
          (fun r ↦ Matrix.mulVecLin
            (linearObservationDescendedMatrix M (fun _ : ℕ ↦ u) a r)) w
          (linearWordDescendedSeed M u a)) :
            linearObservationCoefficientSubring M (fun _ : ℕ ↦ u) a) : K) =
      coordinateRowDual a
        (linearWord (fun r ↦ Matrix.mulVecLin (M r)) w u) := by
  classical
  rw [coordinateRowDual_apply, coordinateRowDual_apply]
  push_cast
  apply Finset.sum_congr rfl
  intro i hi
  rw [linearObservationDescendedRow_coe, linearWord_descended_state_coe]

end WordCoefficientDescent


section ArbitraryCommRingMatrixWords

variable {K ι : Type*} [CommRing K] [Fintype ι]

/-- Over an arbitrary commutative ring, a finite scalar matrix-word
representation has no staircase whose values vanish for `i < j` and remain
nonzero on the diagonal. The finite coefficients are first descended to a
Noetherian subring. -/
theorem commRing_matrixWords_no_upper_evaluation_staircase
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u a : ι → K)
    (x y : ℕ → List (Fin b))
    (hzero : ∀ i j : ℕ, i < j →
      coordinateRowDual a
        (linearWord (fun r ↦ Matrix.mulVecLin (M r)) (x i ++ y j) u) = 0)
    (hdiag : ∀ i : ℕ,
      coordinateRowDual a
        (linearWord (fun r ↦ Matrix.mulVecLin (M r)) (x i ++ y i) u) ≠ 0) :
    False := by
  classical
  let S := linearObservationCoefficientSubring M (fun _ : ℕ ↦ u) a
  letI : IsNoetherianRing S := inferInstance
  let M' := linearObservationDescendedMatrix M (fun _ : ℕ ↦ u) a
  let u' := linearWordDescendedSeed M u a
  let a' := linearObservationDescendedRow M (fun _ : ℕ ↦ u) a
  let T' : Fin b → Module.End S (ι → S) := fun r ↦ Matrix.mulVecLin (M' r)
  let l' : Module.Dual S (ι → S) := coordinateRowDual a'
  let rows : ℕ → ι → S := fun i ↦ linearWord T' (y i) u'
  let cols : ℕ → Module.Dual S (ι → S) :=
    fun i ↦ l'.comp (linearWord T' (x i))
  have hpair (i j : ℕ) :
      ((cols i (rows j) : S) : K) =
        coordinateRowDual a
          (linearWord (fun r ↦ Matrix.mulVecLin (M r)) (x i ++ y j) u) := by
    change ((l' (linearWord T' (x i) (linearWord T' (y j) u')) : S) : K) = _
    rw [← Module.End.mul_apply, ← linearWord_append]
    simpa [S, M', u', a', T', l'] using
      linearWord_descended_evaluation_coe M u a (x i ++ y j)
  apply finiteFree_no_lower_evaluation_staircase rows cols
  · intro i j hij
    apply (Subring.coe_eq_zero_iff S).mp
    rw [hpair]
    exact hzero i j hij
  · intro i hi
    apply hdiag i
    calc
      coordinateRowDual a
          (linearWord (fun r ↦ Matrix.mulVecLin (M r)) (x i ++ y i) u) =
          ((cols i (rows i) : S) : K) := (hpair i i).symm
      _ = 0 := by rw [hi]; rfl

/-- The opposite concatenation staircase is likewise impossible over an
arbitrary commutative coefficient ring. -/
theorem commRing_matrixWords_no_lower_evaluation_staircase
    {b : ℕ} (M : Fin b → Matrix ι ι K) (u a : ι → K)
    (x y : ℕ → List (Fin b))
    (hzero : ∀ i j : ℕ, i < j →
      coordinateRowDual a
        (linearWord (fun r ↦ Matrix.mulVecLin (M r)) (x j ++ y i) u) = 0)
    (hdiag : ∀ i : ℕ,
      coordinateRowDual a
        (linearWord (fun r ↦ Matrix.mulVecLin (M r)) (x i ++ y i) u) ≠ 0) :
    False := by
  classical
  let S := linearObservationCoefficientSubring M (fun _ : ℕ ↦ u) a
  letI : IsNoetherianRing S := inferInstance
  let M' := linearObservationDescendedMatrix M (fun _ : ℕ ↦ u) a
  let u' := linearWordDescendedSeed M u a
  let a' := linearObservationDescendedRow M (fun _ : ℕ ↦ u) a
  let T' : Fin b → Module.End S (ι → S) := fun r ↦ Matrix.mulVecLin (M' r)
  let l' : Module.Dual S (ι → S) := coordinateRowDual a'
  let rows : ℕ → ι → S := fun i ↦ linearWord T' (y i) u'
  let cols : ℕ → Module.Dual S (ι → S) :=
    fun i ↦ l'.comp (linearWord T' (x i))
  have hpair (i j : ℕ) :
      ((cols i (rows j) : S) : K) =
        coordinateRowDual a
          (linearWord (fun r ↦ Matrix.mulVecLin (M r)) (x i ++ y j) u) := by
    change ((l' (linearWord T' (x i) (linearWord T' (y j) u')) : S) : K) = _
    rw [← Module.End.mul_apply, ← linearWord_append]
    simpa [S, M', u', a', T', l'] using
      linearWord_descended_evaluation_coe M u a (x i ++ y j)
  apply finiteFree_no_upper_evaluation_staircase rows cols
  · intro i j hij
    apply (Subring.coe_eq_zero_iff S).mp
    rw [hpair]
    exact hzero i j hij
  · intro i hi
    apply hdiag i
    calc
      coordinateRowDual a
          (linearWord (fun r ↦ Matrix.mulVecLin (M r)) (x i ++ y i) u) =
          ((cols i (rows i) : S) : K) := (hpair i i).symm
      _ = 0 := by rw [hi]; rfl

end ArbitraryCommRingMatrixWords

end IndependentZeroBlocks
