import SierpinskiFormal.ReversibleModuleAction
import SierpinskiFormal.GroupBooleanTranslations
import Mathlib.GroupTheory.FreeGroup.Reduce
import Mathlib.SetTheory.Cardinal.Free

set_option autoImplicit false

/-!
# Finite-module observations of free-group actions

The reduced word of a free-group element gives a canonical signed word, so
the signed-word double-limit theorem applies without a representative
hypothesis.
-/

noncomputable section

namespace IndependentZeroBlocks

/-- Interpret mathlib's Boolean-signed free-group letter as `SignedLetter`.
In `FreeGroup`, `true` denotes a positive letter. -/
def freeGroupPairToSigned {A : Type*} (p : A × Bool) : SignedLetter A :=
  if p.2 then Sum.inl p.1 else Sum.inr p.1

/-- The canonical reduced signed word representing a free-group element. -/
def freeGroupSignedWord {A : Type*} (γ : FreeGroup A) : List (SignedLetter A) := by
  classical
  exact γ.toWord.map freeGroupPairToSigned

/-- The canonical signed word has the original free-group element as its
ordered product. -/
theorem signedWordProduct_freeGroupSignedWord
    {A : Type*} (γ : FreeGroup A) :
    signedWordProduct FreeGroup.of (freeGroupSignedWord γ) = γ := by
  classical
  have haux (w : List (A × Bool)) :
      signedWordProduct FreeGroup.of (w.map freeGroupPairToSigned) =
        FreeGroup.mk w := by
    rw [← FreeGroup.lift_of_apply (FreeGroup.mk w), FreeGroup.lift_mk]
    induction w with
    | nil => simp [signedWordProduct]
    | cons p w ih =>
        cases p with
        | mk r b =>
            cases b <;>
              simp [signedWordProduct, freeGroupPairToSigned, signedGroupLetter]
                at ih ⊢
            · exact ih
            · exact ih
  rw [freeGroupSignedWord, haux, FreeGroup.mk_toWord]

/-- The action of the free group generated by a family of linear
automorphisms. -/
def freeGroupLinearAction {K V A : Type*} [CommRing K] [AddCommGroup V]
    [Module K V] (T : A → V ≃ₗ[K] V) : FreeGroup A →* (V ≃ₗ[K] V) :=
  FreeGroup.lift T

@[simp] theorem freeGroupLinearAction_of
    {K V A : Type*} [CommRing K] [AddCommGroup V] [Module K V]
    (T : A → V ≃ₗ[K] V) (r : A) :
    freeGroupLinearAction T (FreeGroup.of r) = T r := by
  simp [freeGroupLinearAction]

/-- Every free-group element has a finite coordinate-matrix evaluation,
canonically indexed by its reduced signed word. -/
theorem finiteModule_exists_freeGroup_matrix_representation
    {K V A : Type*} [CommRing K] [AddCommGroup V] [Module K V]
    [Module.Finite K V]
    (T : A → V ≃ₗ[K] V) (l : Module.Dual K V) (v : V) :
    ∃ (d : ℕ)
      (M : SignedLetter A → Matrix (Fin d) (Fin d) K)
      (u a : Fin d → K),
      ∀ γ : FreeGroup A,
        coordinateRowDual a
            (linearWord (fun r ↦ Matrix.mulVecLin (M r))
              (freeGroupSignedWord γ) u) =
          l ((freeGroupLinearAction T γ) v) := by
  exact finiteModule_exists_signed_matrix_group_representation
    (freeGroupLinearAction T) FreeGroup.of freeGroupSignedWord
    signedWordProduct_freeGroupSignedWord l v

/-- The intrinsic multiplication kernel of a finite-module free-group
observation has the Boolean double-limit property. -/
theorem finiteModule_freeGroupNonzeroBool_hasBooleanDoubleLimitProperty
    {K V A : Type*} [CommRing K] [AddCommGroup V] [Module K V]
    [Module.Finite K V] [Fintype A]
    (T : A → V ≃ₗ[K] V) (l : Module.Dual K V) (v : V) :
    HasBooleanDoubleLimitProperty
      (fun γ δ : FreeGroup A ↦
        nonzeroBool (l ((freeGroupLinearAction T (γ * δ)) v))) := by
  exact finiteModule_groupNonzeroBool_hasBooleanDoubleLimitProperty_of_signed_reps
    (freeGroupLinearAction T) FreeGroup.of freeGroupSignedWord
    signedWordProduct_freeGroupSignedWord l v

/-- The same result in the right-row notation used by the intrinsic Boolean
group-flow development. -/
theorem finiteModule_freeGroup_booleanGroupRightRow_hasBooleanDoubleLimitProperty
    {K V A : Type*} [CommRing K] [AddCommGroup V] [Module K V]
    [Module.Finite K V] [Fintype A]
    (T : A → V ≃ₗ[K] V) (l : Module.Dual K V) (v : V) :
    HasBooleanDoubleLimitProperty
      (booleanGroupRightRow
        (fun γ : FreeGroup A ↦
          nonzeroBool (l ((freeGroupLinearAction T γ) v)))) := by
  have h := finiteModule_freeGroupNonzeroBool_hasBooleanDoubleLimitProperty T l v
  intro x y rowLimit columnLimit rowOuter columnOuter
    hrow hcolumn hrowOuter hcolumnOuter
  symm
  apply (h y x columnLimit rowLimit columnOuter rowOuter)
  · simpa [booleanGroupRightRow] using hcolumn
  · simpa [booleanGroupRightRow] using hrow
  · exact hcolumnOuter
  · exact hrowOuter

/-- A free group on a finite alphabet is countable, as required by the
countable Boolean group-flow results. -/
theorem freeGroup_countable_of_fintype (A : Type*) [Fintype A] :
    Countable (FreeGroup A) := by
  infer_instance

/-- The canonical free generators generate the whole free group. -/
theorem freeGroup_closure_range_of_eq_top (A : Type*) :
    Subgroup.closure (Set.range (FreeGroup.of : A → FreeGroup A)) = ⊤ :=
  FreeGroup.closure_range_of A

/-- Finite Boolean combinations may use different finite modules and
different automorphism representations in each coordinate. -/
theorem finiteModule_freeGroup_booleanCombine_rightRow_hasBooleanDoubleLimitProperty
    {K A : Type*} {m : ℕ} [CommRing K] [Fintype A]
    (V : Fin m → Type*)
    [∀ k, AddCommGroup (V k)] [∀ k, Module K (V k)]
    [∀ k, Module.Finite K (V k)]
    (op : (Fin m → Bool) → Bool)
    (T : ∀ k, A → V k ≃ₗ[K] V k)
    (l : ∀ k, Module.Dual K (V k)) (v : ∀ k, V k) :
    HasBooleanDoubleLimitProperty
      (booleanGroupRightRow
        (fun γ : FreeGroup A ↦ op (fun k ↦
          nonzeroBool (l k ((freeGroupLinearAction (T k) γ) (v k)))))) := by
  have hcombine := hasBooleanDoubleLimitProperty_booleanCombine op
    (fun k ↦ booleanGroupRightRow
      (fun γ : FreeGroup A ↦
        nonzeroBool (l k ((freeGroupLinearAction (T k) γ) (v k)))))
    (fun k ↦
      finiteModule_freeGroup_booleanGroupRightRow_hasBooleanDoubleLimitProperty
        (T k) (l k) (v k))
  exact hcombine

end IndependentZeroBlocks
