import Publication

#check FiniteMonoidMortality.exists_minimum_rank_word_real_of_finite
#print axioms FiniteMonoidMortality.exists_minimum_rank_word_real_of_finite
#check FiniteMonoidMortality.exists_minimum_rank_word_rational_of_finite
#print axioms FiniteMonoidMortality.exists_minimum_rank_word_rational_of_finite
#check FiniteMonoidMortality.exists_improved_short_zero_word_of_finite_real_monoid
#print axioms FiniteMonoidMortality.exists_improved_short_zero_word_of_finite_real_monoid
#check FiniteMonoidMortality.exists_improved_short_zero_word_of_finite_rational_monoid
#print axioms FiniteMonoidMortality.exists_improved_short_zero_word_of_finite_rational_monoid
#check FiniteMonoidMortality.exists_zero_word_length_le_four_real
#print axioms FiniteMonoidMortality.exists_zero_word_length_le_four_real
#check FiniteMonoidMortality.exists_zero_word_length_le_four_rational
#print axioms FiniteMonoidMortality.exists_zero_word_length_le_four_rational
#check FiniteMonoidMortality.mortalityExample_threshold_four
#print axioms FiniteMonoidMortality.mortalityExample_threshold_four
#check FiniteMonoidMortality.exists_zero_word_of_invariant_flag
#print axioms FiniteMonoidMortality.exists_zero_word_of_invariant_flag
#check FiniteMonoidMortality.exists_zero_word_prescribed_small_factors
#print axioms FiniteMonoidMortality.exists_zero_word_prescribed_small_factors
#check FiniteMonoidMortality.exists_zero_word_linear_bound_of_small_factors
#print axioms FiniteMonoidMortality.exists_zero_word_linear_bound_of_small_factors
#check FiniteMonoidMortality.sharp_small_block_threshold
#print axioms FiniteMonoidMortality.sharp_small_block_threshold
#check FiniteMonoidMortality.mortalityRotation_irreducible
#print axioms FiniteMonoidMortality.mortalityRotation_irreducible
#check FiniteMonoidMortality.bounded_periodic_mortality_no_uniform_bound
#print axioms FiniteMonoidMortality.bounded_periodic_mortality_no_uniform_bound
#check FiniteMonoidMortality.exists_minimum_rank_slp_real_of_finite
#print axioms FiniteMonoidMortality.exists_minimum_rank_slp_real_of_finite
#check FiniteMonoidMortality.exists_minimum_rank_slp_rational_of_finite
#print axioms FiniteMonoidMortality.exists_minimum_rank_slp_rational_of_finite
#check FiniteMonoidMortality.wordProgramValue_correct
#print axioms FiniteMonoidMortality.wordProgramValue_correct
#check FiniteMonoidMortality.mortalitySLPGateBound_le_cubic
#print axioms FiniteMonoidMortality.mortalitySLPGateBound_le_cubic
#check FiniteMonoidMortality.minimumRankBound_full
#print axioms FiniteMonoidMortality.minimumRankBound_full
#check FiniteMonoidMortality.minimumRankBound_zero
#print axioms FiniteMonoidMortality.minimumRankBound_zero
#check FiniteMonoidMortality.mortalityBudget_comparison
#print axioms FiniteMonoidMortality.mortalityBudget_comparison
#check FiniteMonoidMortality.linearWord_nil
#print axioms FiniteMonoidMortality.linearWord_nil
#check FiniteMonoidMortality.factorMortalityBound_one
#print axioms FiniteMonoidMortality.factorMortalityBound_one
#check FiniteMonoidMortality.extendProgramLetter_root
#print axioms FiniteMonoidMortality.extendProgramLetter_root
