import Publication

#print IndependentZeroBlocks.exists_short_zero_word_of_finite_real_monoid
#print axioms IndependentZeroBlocks.exists_short_zero_word_of_finite_real_monoid
#print IndependentZeroBlocks.exists_short_zero_word_of_finite_rational_monoid
#print axioms IndependentZeroBlocks.exists_short_zero_word_of_finite_rational_monoid
#print IndependentZeroBlocks.exists_short_rank_decreasing_sandwich_of_finite
#print axioms IndependentZeroBlocks.exists_short_rank_decreasing_sandwich_of_finite
#print IndependentZeroBlocks.finiteMortalityBound
