import Publication

#print FiniteMonoidMortality.exists_short_zero_word_of_finite_real_monoid
#print axioms FiniteMonoidMortality.exists_short_zero_word_of_finite_real_monoid
#print FiniteMonoidMortality.exists_short_zero_word_of_finite_rational_monoid
#print axioms FiniteMonoidMortality.exists_short_zero_word_of_finite_rational_monoid
#print FiniteMonoidMortality.exists_short_rank_decreasing_sandwich_of_finite
#print axioms FiniteMonoidMortality.exists_short_rank_decreasing_sandwich_of_finite
#print FiniteMonoidMortality.finiteMortalityBound
